import { createHash } from "node:crypto";
import type { Tx } from "../../kernel";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const HASH=/^[0-9a-f]{64}$/;
type Row=Readonly<Record<string,unknown>>;

export interface IndiaFinalComponentTaxFiscalSourceInput { readonly tenantId:string; readonly propertyNode:string; readonly reservationId:string; readonly folioId:string; readonly journalId:string }
export interface IndiaFinalComponentTaxFiscalSourceRoomNight { readonly ordinal:string; readonly businessDate:string; readonly transactionValueMinor:string; readonly slabUptoMinor:string|null; readonly aggregateRateBasisPoints:number; readonly itcEligible:boolean; readonly taxMinor:string }
export interface IndiaFinalComponentTaxFiscalSourceComponent { readonly roomNightOrdinal:number; readonly componentOrdinal:number; readonly componentIdentity:"igst"|"cgst"|"sgst"|"utgst"; readonly rateBasisPoints:number; readonly taxAmountMinor:string }
export interface IndiaFinalComponentTaxFiscalSourceJournalLine { readonly id:string; readonly seq:number; readonly accountId:string; readonly accountRole:string; readonly folioId:string|null; readonly txCode:string; readonly description:string; readonly amountMinor:string; readonly quantity:string; readonly businessDate:string; readonly currency:"INR"; readonly taxDetail:unknown|null }
export interface IndiaFinalComponentTaxFiscalSourceResult {
  readonly state:"eligible_current_posted_source"; readonly postingBindingId:string; readonly journalId:string;
  readonly taxId:string; readonly taxGeneration:number; readonly taxEvidenceHash:string; readonly valuationId:string;
  readonly valuationGeneration:number; readonly finalValuationEvidenceHash:string; readonly applicabilityId:string;
  readonly applicabilityEvidenceHash:string; readonly reservationId:string; readonly folioId:string; readonly guestAccountId:string;
  readonly propertyNode:string; readonly businessDate:string; readonly currency:"INR"; readonly transactionValueMinor:string;
  readonly taxMinor:string; readonly grandTotalMinor:string; readonly componentFamily:"igst"|"cgst_sgst"|"cgst_utgst";
  readonly predecessorHashes:Readonly<{section14:string;levyComponentIdentity:string;reservationLineage:string;attributionSnapshot:string}>;
  readonly roomNights:readonly IndiaFinalComponentTaxFiscalSourceRoomNight[];
  readonly components:readonly IndiaFinalComponentTaxFiscalSourceComponent[];
  readonly journalLines:readonly IndiaFinalComponentTaxFiscalSourceJournalLine[]; readonly sourceEvidenceHash:string;
}
export class IndiaFinalComponentTaxFiscalSourceValidationError extends Error { constructor(m:string){super(m);this.name="IndiaFinalComponentTaxFiscalSourceValidationError"} }
export class IndiaFinalComponentTaxFiscalSourceNotFoundError extends Error { constructor(m:string){super(m);this.name="IndiaFinalComponentTaxFiscalSourceNotFoundError"} }
export class IndiaFinalComponentTaxFiscalSourceConflictError extends Error { constructor(m:string){super(m);this.name="IndiaFinalComponentTaxFiscalSourceConflictError"} }

function exact(v:unknown,keys:readonly string[]):Row{if(typeof v!=="object"||v===null||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype||Object.getOwnPropertySymbols(v).length)throw new IndiaFinalComponentTaxFiscalSourceValidationError("input must be an exact plain object");const d=Object.getOwnPropertyDescriptors(v),a=Object.keys(d).sort(),e=[...keys].sort();if(a.length!==e.length||a.some((k,i)=>k!==e[i])||Object.values(d).some(x=>x.get||x.set||!x.enumerable||!("value" in x)))throw new IndiaFinalComponentTaxFiscalSourceValidationError("input shape is invalid");return v as Row}
function id(v:unknown,n:string):string{if(typeof v!=="string"||!UUID.test(v))throw new IndiaFinalComponentTaxFiscalSourceValidationError(`${n} must be a lowercase UUID`);return v}
function str(v:unknown,n:string):string{if(typeof v!=="string")throw new IndiaFinalComponentTaxFiscalSourceConflictError(`invalid stored ${n}`);return v}
function hash(v:unknown,n:string):string{const x=str(v,n);if(!HASH.test(x))throw new IndiaFinalComponentTaxFiscalSourceConflictError(`invalid stored ${n}`);return x}
function num(v:unknown,n:string):number{const x=Number(v);if(!Number.isSafeInteger(x)||x<0)throw new IndiaFinalComponentTaxFiscalSourceConflictError(`invalid stored ${n}`);return x}
function freeze<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const x of Object.values(v as Record<string,unknown>))freeze(x);Object.freeze(v)}return v}
function digest(v:unknown):string{return createHash("sha256").update(JSON.stringify(v)).digest("hex")}
function keys(v:Row|undefined,expected:readonly string[]):boolean{return !!v&&Object.keys(v).sort().join("\0")===[...expected].sort().join("\0")}
export class IndiaFinalComponentTaxFiscalSourceService {
 async resolve(tx:Tx,raw:IndiaFinalComponentTaxFiscalSourceInput):Promise<IndiaFinalComponentTaxFiscalSourceResult>{
  if(typeof tx!=="function")throw new IndiaFinalComponentTaxFiscalSourceValidationError("tenant transaction is unavailable");
  const x=exact(raw,["tenantId","propertyNode","reservationId","folioId","journalId"]),tenant=id(x.tenantId,"tenantId"),property=id(x.propertyNode,"propertyNode"),reservation=id(x.reservationId,"reservationId"),folio=id(x.folioId,"folioId"),journal=id(x.journalId,"journalId");
  const bindings=await tx<Row[]>`SELECT id::text FROM public.india_gst_accommodation_final_component_tax_journal_binding WHERE tenant_id=${tenant}::uuid AND tenant_id=current_setting('app.tenant_id',true)::uuid AND property_node=${property}::uuid AND reservation_id=${reservation}::uuid AND folio_id=${folio}::uuid AND journal_id=${journal}::uuid`;
  if(bindings.length===0)throw new IndiaFinalComponentTaxFiscalSourceNotFoundError("fiscal source was not found");
  if(bindings.length!==1)throw new IndiaFinalComponentTaxFiscalSourceConflictError("fiscal source binding is ambiguous");
  const roots=await tx<Row[]>`SELECT b.id::text posting_binding_id,b.tax_id::text,b.tax_generation,b.tax_evidence_hash,b.valuation_id::text,b.valuation_generation,b.applicability_id::text,b.reservation_id::text,b.folio_id::text,b.guest_account_id::text,b.property_node::text,b.business_date::text,b.currency::text,t.generation current_tax_generation,t.evidence_hash current_tax_evidence_hash,t.transaction_value_minor::text,t.tax_minor::text,t.grand_total_minor::text,t.component_family,t.selected_extension_id::text,t.selected_extension_version,t.section14_evidence_hash,t.levy_component_identity_evidence_hash,t.reservation_lineage_evidence_hash,t.attribution_snapshot_evidence_hash,t.final_valuation_evidence_hash,t.quoted_rate_applicability_evidence_hash,v.evidence_hash valuation_evidence_hash,v.generation valuation_current_generation,v.property_node::text valuation_property,v.reservation_id::text valuation_reservation,v.folio_id::text valuation_folio,v.folio_account_id::text valuation_account,v.currency::text valuation_currency,v.disposition,a.evidence_hash applicability_evidence_hash,a.selected_content_hash,a.property_node::text applicability_property,a.reservation_id::text applicability_reservation,a.folio_id::text applicability_folio,a.final_valuation_id::text applicability_valuation,a.component_family applicability_family,j.kind journal_kind,j.reverses::text journal_reverses,j.source journal_source,j.property_node::text journal_property,j.business_date::text journal_business_date,j.currency::text journal_currency,fa.property_node::text account_property,fa.currency::text account_currency,fa.role account_role,f.account_id::text folio_account,r.property_node::text reservation_property FROM public.india_gst_accommodation_final_component_tax_journal_binding b JOIN public.india_gst_accommodation_final_component_tax t ON t.tenant_id=b.tenant_id AND t.id=b.tax_id JOIN public.india_gst_accommodation_final_valuation v ON v.tenant_id=t.tenant_id AND v.id=t.valuation_id JOIN public.india_gst_accommodation_quoted_rate_applicability a ON a.tenant_id=t.tenant_id AND a.id=t.applicability_id JOIN public.journal j ON j.tenant_id=b.tenant_id AND j.id=b.journal_id JOIN public.folio f ON f.tenant_id=b.tenant_id AND f.id=b.folio_id JOIN public.account fa ON fa.tenant_id=f.tenant_id AND fa.id=f.account_id JOIN public.reservation r ON r.tenant_id=b.tenant_id AND r.id=b.reservation_id WHERE b.tenant_id=${tenant}::uuid AND b.tenant_id=current_setting('app.tenant_id',true)::uuid AND b.property_node=${property}::uuid AND b.reservation_id=${reservation}::uuid AND b.folio_id=${folio}::uuid AND b.journal_id=${journal}::uuid`;
  if(roots.length!==1)throw new IndiaFinalComponentTaxFiscalSourceConflictError("fiscal source ancestry is incomplete or ambiguous");const r=roots[0]!;
  const taxId=id(r.tax_id,"tax id"),valuationId=id(r.valuation_id,"valuation id"),applicabilityId=id(r.applicability_id,"applicability id"),guestAccount=id(r.guest_account_id,"guest account id");
  const taxGeneration=num(r.tax_generation,"tax generation"),valuationGeneration=num(r.valuation_generation,"valuation generation"),taxHash=hash(r.tax_evidence_hash,"tax evidence hash"),valuationHash=hash(r.final_valuation_evidence_hash,"valuation evidence hash"),appHash=hash(r.quoted_rate_applicability_evidence_hash,"applicability evidence hash");
  if(Number(r.current_tax_generation)!==taxGeneration||r.current_tax_evidence_hash!==taxHash||r.property_node!==property||r.reservation_id!==reservation||r.folio_id!==folio||r.valuation_property!==property||r.valuation_reservation!==reservation||r.valuation_folio!==folio||r.applicability_property!==property||r.applicability_reservation!==reservation||r.applicability_folio!==folio||r.reservation_property!==property||r.account_property!==property||r.valuation_account!==guestAccount||r.folio_account!==guestAccount||r.account_role!=="guest"||r.currency!=="INR"||r.valuation_currency!=="INR"||r.account_currency!=="INR"||r.journal_currency!=="INR"||r.journal_property!==property||r.journal_business_date!==r.business_date||r.journal_kind!=="charge"||r.journal_reverses!==null||r.disposition!=="ordinary_final"||r.applicability_valuation!==valuationId||r.applicability_family!==r.component_family||r.valuation_evidence_hash!==valuationHash||r.applicability_evidence_hash!==appHash||Number(r.valuation_current_generation)!==valuationGeneration)throw new IndiaFinalComponentTaxFiscalSourceConflictError("persisted fiscal-source lineage is inconsistent");
  const source=r.journal_source as Row;if(!source||source.interface!=="financials.india-final-component-tax.post"||source.tax_id!==taxId||Object.keys(source).length!==2)throw new IndiaFinalComponentTaxFiscalSourceConflictError("journal source is inconsistent");
  const stale=await tx<Row[]>`SELECT (EXISTS(SELECT 1 FROM public.india_gst_accommodation_final_component_tax s WHERE s.tenant_id=${tenant}::uuid AND s.supersedes_tax_id=${taxId}::uuid) OR EXISTS(SELECT 1 FROM public.india_gst_accommodation_final_valuation s WHERE s.tenant_id=${tenant}::uuid AND s.supersedes_valuation_id=${valuationId}::uuid) OR EXISTS(SELECT 1 FROM public.india_gst_final_component_tax_journal_reversal_binding z WHERE z.tenant_id=${tenant}::uuid AND z.original_journal_id=${journal}::uuid)) stale`;
  if(stale[0]?.stale!==false)throw new IndiaFinalComponentTaxFiscalSourceConflictError("fiscal source is no longer current or has been reversed");
  const nightsRaw=await tx<Row[]>`SELECT ordinal,business_date::text,final_value_minor::text,slab_upto_minor::text,aggregate_rate_basis_points,itc_eligible,tax_minor::text FROM public.india_gst_accommodation_final_component_tax_room_night WHERE tenant_id=${tenant}::uuid AND tax_id=${taxId}::uuid ORDER BY ordinal`;
  if(nightsRaw.length<1||nightsRaw.length>366)throw new IndiaFinalComponentTaxFiscalSourceConflictError("room-night evidence is incomplete");
  const nights=nightsRaw.map((n,i)=>{if(Number(n.ordinal)!==i)throw new IndiaFinalComponentTaxFiscalSourceConflictError("room-night ordinals are not contiguous");return {ordinal:String(n.ordinal),businessDate:str(n.business_date,"business date"),transactionValueMinor:str(n.final_value_minor,"night value"),slabUptoMinor:n.slab_upto_minor===null?null:str(n.slab_upto_minor,"slab"),aggregateRateBasisPoints:num(n.aggregate_rate_basis_points,"aggregate rate"),itcEligible:n.itc_eligible===true,taxMinor:str(n.tax_minor,"night tax")}});
  const compsRaw=await tx<Row[]>`SELECT room_night_ordinal,component_ordinal,component_identity,rate_basis_points,tax_amount_minor::text FROM public.india_gst_accommodation_final_component_tax_component WHERE tenant_id=${tenant}::uuid AND tax_id=${taxId}::uuid ORDER BY room_night_ordinal,component_ordinal`;
  const storedFamily=r.component_family;if(storedFamily!=="igst"&&storedFamily!=="cgst_sgst"&&storedFamily!=="cgst_utgst")throw new IndiaFinalComponentTaxFiscalSourceConflictError("component family is invalid");const family:IndiaFinalComponentTaxFiscalSourceResult["componentFamily"]=storedFamily;const ids=family==="igst"?["igst"]:family==="cgst_sgst"?["cgst","sgst"]:["cgst","utgst"];
  if(compsRaw.length!==nights.length*ids.length)throw new IndiaFinalComponentTaxFiscalSourceConflictError("component evidence is incomplete");
  const comps=compsRaw.map((c,i)=>{const night=Math.floor(i/ids.length),ord=i%ids.length;if(Number(c.room_night_ordinal)!==night||Number(c.component_ordinal)!==ord||c.component_identity!==ids[ord])throw new IndiaFinalComponentTaxFiscalSourceConflictError("component topology is inconsistent");return {roomNightOrdinal:night,componentOrdinal:ord,componentIdentity:c.component_identity as "igst"|"cgst"|"sgst"|"utgst",rateBasisPoints:num(c.rate_basis_points,"component rate"),taxAmountMinor:str(c.tax_amount_minor,"component tax")}});
  let tv=0n,tax=0n;for(const [i,n] of nights.entries()){const cs=comps.filter(c=>c.roomNightOrdinal===i);const nt=cs.reduce((s,c)=>s+BigInt(c.taxAmountMinor),0n);if(nt!==BigInt(n.taxMinor)||cs.some(c=>c.rateBasisPoints*ids.length!==n.aggregateRateBasisPoints))throw new IndiaFinalComponentTaxFiscalSourceConflictError("component amounts or rates do not reconcile");tv+=BigInt(n.transactionValueMinor);tax+=nt}
  if(tv.toString()!==r.transaction_value_minor||tax.toString()!==r.tax_minor||(tv+tax).toString()!==r.grand_total_minor)throw new IndiaFinalComponentTaxFiscalSourceConflictError("tax totals do not reconcile");
  const roomJson=nights.map((n,i)=>({ordinal:n.ordinal,businessDate:n.businessDate,transactionValueMinor:n.transactionValueMinor,slab:{uptoMinor:n.slabUptoMinor===null?null:Number(n.slabUptoMinor),aggregateRateBasisPoints:n.aggregateRateBasisPoints,components:comps.filter(c=>c.roomNightOrdinal===i).map(c=>({identity:c.componentIdentity,rateBasisPoints:c.rateBasisPoints,taxMinor:c.taxAmountMinor}))},taxMinor:n.taxMinor}));
  const canonicalTaxHash=digest({tenant,property,reservation,folio,valuationId,generation:valuationGeneration,roomNights:roomJson,taxMinor:String(r.tax_minor),grandTotalMinor:String(r.grand_total_minor),predecessorHashes:{finalValuation:valuationHash,quotedRateApplicability:appHash,section14:hash(r.section14_evidence_hash,"section14 hash"),levyComponentIdentity:hash(r.levy_component_identity_evidence_hash,"levy hash"),reservationLineage:hash(r.reservation_lineage_evidence_hash,"lineage hash"),attributionSnapshot:hash(r.attribution_snapshot_evidence_hash,"attribution hash")}});
  if(canonicalTaxHash!==taxHash)throw new IndiaFinalComponentTaxFiscalSourceConflictError("component-tax evidence does not byte-match persisted truth");
  const linesRaw=await tx<Row[]>`SELECT l.id::text,l.seq,l.account_id::text,a.role account_role,l.folio_id::text,l.tx_code,l.description,l.amount_minor::text,l.quantity::text,l.business_date::text,l.currency::text,l.tax_detail FROM public.posting_line l JOIN public.account a ON a.tenant_id=l.tenant_id AND a.id=l.account_id WHERE l.tenant_id=${tenant}::uuid AND l.journal_id=${journal}::uuid ORDER BY l.seq,l.id`;
  const lines=linesRaw.map((l,i)=>{if(Number(l.seq)!==i+1||l.business_date!==r.business_date||l.currency!=="INR")throw new IndiaFinalComponentTaxFiscalSourceConflictError("journal line topology is inconsistent");return {id:id(l.id,"line id"),seq:i+1,accountId:id(l.account_id,"line account"),accountRole:str(l.account_role,"account role"),folioId:l.folio_id===null?null:id(l.folio_id,"line folio"),txCode:str(l.tx_code,"tx code"),description:str(l.description,"line description"),amountMinor:str(l.amount_minor,"line amount"),quantity:str(l.quantity,"line quantity"),businessDate:str(l.business_date,"line date"),currency:"INR" as const,taxDetail:l.tax_detail??null}});
  const positiveIdentities=new Set(comps.filter(c=>BigInt(c.taxAmountMinor)>0n).map(c=>c.componentIdentity));
  if(lines.length!==2+positiveIdentities.size||lines[0]?.accountId!==guestAccount||lines[0]?.folioId!==folio||lines[0]?.amountMinor!==r.grand_total_minor||lines.slice(1).some(l=>l.folioId!==null||l.taxDetail!==null)||lines.reduce((s,l)=>s+BigInt(l.amountMinor),0n)!==0n)throw new IndiaFinalComponentTaxFiscalSourceConflictError("journal is not the exact balanced posting topology");
  if(lines.filter(l=>l.taxDetail!==null).length!==1)throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical tax detail must exist only on the guest root");
  const detail=lines[0]!.taxDetail as Row;
  const dTax=detail?.tax as Row,dVal=detail?.valuation as Row,dApp=detail?.applicability as Row,dPosting=detail?.posting as Row,dTotals=detail?.totals as Row,dJurisdiction=detail?.jurisdiction as Row,dRevenue=detail?.revenueRoute as Row,dComponents=detail?.components;
  if(!keys(detail,["schemaVersion","tax","valuation","applicability","posting","totals","componentFamily","jurisdiction","revenueRoute","components"])||!keys(dTax,["taxId","taxGeneration","evidenceHash"])||!keys(dVal,["valuationId","valuationGeneration","evidenceHash"])||!keys(dApp,["applicabilityId","evidenceHash"])||!keys(dPosting,["propertyNode","reservationId","folioId","journalId","currency"])||!keys(dTotals,["transactionValueMinor","taxMinor","grandTotalMinor"])||!keys(dJurisdiction,["extensionId","ownerTenantId","key","version","contentHash"])||!keys(dRevenue,["mappingId","semanticCode","txCode","creditAccountId"])||detail?.schemaVersion!=="india_accommodation_component_tax_v1"||dTax?.taxId!==taxId||Number(dTax?.taxGeneration)!==taxGeneration||dTax?.evidenceHash!==taxHash||dVal?.valuationId!==valuationId||Number(dVal?.valuationGeneration)!==valuationGeneration||dVal?.evidenceHash!==valuationHash||dApp?.applicabilityId!==applicabilityId||dApp?.evidenceHash!==appHash||dPosting?.propertyNode!==property||dPosting?.reservationId!==reservation||dPosting?.folioId!==folio||dPosting?.journalId!==journal||dPosting?.currency!=="INR"||dTotals?.transactionValueMinor!==r.transaction_value_minor||dTotals?.taxMinor!==r.tax_minor||dTotals?.grandTotalMinor!==r.grand_total_minor||detail?.componentFamily!==family||dJurisdiction?.extensionId!==r.selected_extension_id||dJurisdiction?.ownerTenantId!==null||dJurisdiction?.key!=="in-gst-lodging"||Number(dJurisdiction?.version)!==Number(r.selected_extension_version)||dJurisdiction?.contentHash!==r.selected_content_hash||!Array.isArray(dComponents)||dRevenue?.semanticCode!=="room_revenue"||dRevenue?.creditAccountId!==lines[1]?.accountId||dRevenue?.txCode!==lines[1]?.txCode||lines[1]?.amountMinor!==(-tv).toString()||lines[1]?.accountRole!=="revenue")throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical tax detail is inconsistent");
  const totals=new Map<string,bigint>();for(const c of comps)totals.set(c.componentIdentity,(totals.get(c.componentIdentity)??0n)+BigInt(c.taxAmountMinor));
  if(dComponents.length!==ids.length)throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical component route set is incomplete");let lineIndex=2;
  type RouteExpectation=Readonly<{mappingId:string;semanticKind:"revenue"|"tax";semanticCode:string;txCode:string;creditAccountId:string;accountRole:"revenue"|"tax_payable"}>;
  const routeExpectations:RouteExpectation[]=[{mappingId:id(dRevenue.mappingId,"revenue mapping id"),semanticKind:"revenue",semanticCode:"room_revenue",txCode:str(dRevenue.txCode,"revenue tx code"),creditAccountId:id(dRevenue.creditAccountId,"revenue credit account"),accountRole:"revenue"}];
  for(const [i,identity] of ids.entries()){const dc=dComponents[i] as Row,amount=totals.get(identity)??0n,semantic=identity.toUpperCase(),route=dc?.route as Row|null;if(!keys(dc,["componentIdentity","semanticCode","amountMinor","route"])||dc?.componentIdentity!==identity||dc?.semanticCode!==semantic||dc?.amountMinor!==amount.toString())throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical component detail is inconsistent");if(amount===0n){if(route!==null)throw new IndiaFinalComponentTaxFiscalSourceConflictError("zero component has a route");continue}const line=lines[lineIndex++];if(!route||!keys(route,["mappingId","semanticCode","txCode","creditAccountId"])||route.semanticCode!==semantic||route.creditAccountId!==line?.accountId||route.txCode!==line?.txCode||line?.amountMinor!==(-amount).toString()||line?.accountRole!=="tax_payable")throw new IndiaFinalComponentTaxFiscalSourceConflictError("component credit route is inconsistent");routeExpectations.push({mappingId:id(route.mappingId,"component mapping id"),semanticKind:"tax",semanticCode:semantic,txCode:str(route.txCode,"component tx code"),creditAccountId:id(route.creditAccountId,"component credit account"),accountRole:"tax_payable"})}
  if(new Set(routeExpectations.map(route=>route.mappingId)).size!==routeExpectations.length)throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical route mappings are duplicated");
  const routeRows=await tx<Row[]>`SELECT m.id::text,m.semantic_kind,m.semantic_code,m.tx_code,tr.credit_account_id::text,a.role account_role FROM public.tax_semantic_route m JOIN public.tx_code_route tr ON tr.tenant_id=m.tenant_id AND tr.property_node=m.property_node AND tr.currency=m.currency AND tr.tx_code=m.tx_code JOIN public.account a ON a.tenant_id=tr.tenant_id AND a.id=tr.credit_account_id AND a.property_node=m.property_node AND a.currency=m.currency WHERE m.tenant_id=${tenant}::uuid AND m.property_node=${property}::uuid AND m.currency='INR' AND m.jurisdiction_extension_id=${String(r.selected_extension_id)}::uuid AND m.jurisdiction_owner_tenant_id IS NULL AND m.jurisdiction_key='in-gst-lodging' AND m.jurisdiction_version=${Number(r.selected_extension_version)} AND m.jurisdiction_content_hash=${String(r.selected_content_hash)} AND m.id IN (SELECT value::uuid FROM jsonb_array_elements_text(${JSON.stringify(routeExpectations.map(route=>route.mappingId))}::jsonb))`;
  if(routeRows.length!==routeExpectations.length)throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical route set is incomplete");
  const actualRoutes=new Map(routeRows.map(row=>[String(row.id),row]));
  for(const expected of routeExpectations){const actual=actualRoutes.get(expected.mappingId);if(!actual||actual.semantic_kind!==expected.semanticKind||actual.semantic_code!==expected.semanticCode||actual.tx_code!==expected.txCode||actual.credit_account_id!==expected.creditAccountId||actual.account_role!==expected.accountRole)throw new IndiaFinalComponentTaxFiscalSourceConflictError("canonical route binding is inconsistent")}
  // PostgreSQL jsonb does not preserve the producer's insertion order. Rebuild
  // the already shape- and value-authenticated detail in the canonical order
  // required by downstream exact-record consumers before freezing or hashing it.
  const canonicalTaxDetail={
    schemaVersion:detail.schemaVersion,
    tax:{taxId:dTax.taxId,taxGeneration:dTax.taxGeneration,evidenceHash:dTax.evidenceHash},
    valuation:{valuationId:dVal.valuationId,valuationGeneration:dVal.valuationGeneration,evidenceHash:dVal.evidenceHash},
    applicability:{applicabilityId:dApp.applicabilityId,evidenceHash:dApp.evidenceHash},
    posting:{propertyNode:dPosting.propertyNode,reservationId:dPosting.reservationId,folioId:dPosting.folioId,journalId:dPosting.journalId,currency:dPosting.currency},
    totals:{transactionValueMinor:dTotals.transactionValueMinor,taxMinor:dTotals.taxMinor,grandTotalMinor:dTotals.grandTotalMinor},
    componentFamily:detail.componentFamily,
    jurisdiction:{extensionId:dJurisdiction.extensionId,ownerTenantId:dJurisdiction.ownerTenantId,key:dJurisdiction.key,version:dJurisdiction.version,contentHash:dJurisdiction.contentHash},
    revenueRoute:{mappingId:dRevenue.mappingId,semanticCode:dRevenue.semanticCode,txCode:dRevenue.txCode,creditAccountId:dRevenue.creditAccountId},
    components:dComponents.map((component)=>{const route=component.route as Row|null;return {componentIdentity:component.componentIdentity,semanticCode:component.semanticCode,amountMinor:component.amountMinor,route:route===null?null:{mappingId:route.mappingId,semanticCode:route.semanticCode,txCode:route.txCode,creditAccountId:route.creditAccountId}}}),
  };
  const canonicalLines=lines.map((line,index)=>index===0?{...line,taxDetail:canonicalTaxDetail}:line);
  const predecessors={section14:hash(r.section14_evidence_hash,"section14 hash"),levyComponentIdentity:hash(r.levy_component_identity_evidence_hash,"levy hash"),reservationLineage:hash(r.reservation_lineage_evidence_hash,"lineage hash"),attributionSnapshot:hash(r.attribution_snapshot_evidence_hash,"attribution hash")};
  const body={state:"eligible_current_posted_source" as const,postingBindingId:id(r.posting_binding_id,"binding id"),journalId:journal,taxId,taxGeneration,taxEvidenceHash:taxHash,valuationId,valuationGeneration,finalValuationEvidenceHash:valuationHash,applicabilityId,applicabilityEvidenceHash:appHash,reservationId:reservation,folioId:folio,guestAccountId:guestAccount,propertyNode:property,businessDate:str(r.business_date,"business date"),currency:"INR" as const,transactionValueMinor:str(r.transaction_value_minor,"transaction value"),taxMinor:str(r.tax_minor,"tax total"),grandTotalMinor:str(r.grand_total_minor,"grand total"),componentFamily:family,predecessorHashes:predecessors,roomNights:nights,components:comps,journalLines:canonicalLines};
  return freeze({...body,sourceEvidenceHash:digest({tenantId:tenant,...body})});
 }
}
