import { ApprovalService, recordFact, type AuditEnvelope, type Database, type EventBus, type JsonValue, type PostgresIdempotency, type Tx } from "../../kernel";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const KEY=/^[\x21-\x7e]{8,200}$/;
const MONEY=/^-?(?:0|[1-9][0-9]*)$/;
const CURRENCY=/^[A-Z]{3}$/;
export interface ReceivablePreviewInput { readonly tenantId:string; readonly propertyNode:string; readonly folioId:string; readonly receivableAccountId:string; }
export interface ReceivableTargetListInput { readonly tenantId:string; readonly propertyNode:string; }
export interface ReceivableTransferInput { readonly tenantId:string; readonly folioId:string; readonly receivableAccountId:string; readonly approvalId?:string|null; readonly reason:string; readonly idempotencyKey:string; readonly envelope:AuditEnvelope; }
export interface RequestReceivableApprovalInput { readonly tenantId:string; readonly folioId:string; readonly receivableAccountId:string; readonly idempotencyKey:string; readonly envelope:AuditEnvelope; }
export interface DecideReceivableApprovalInput { readonly tenantId:string; readonly folioId:string; readonly approvalId:string; readonly idempotencyKey:string; readonly envelope:AuditEnvelope; }
export interface ReceivablePreview { readonly folioId:string; readonly receivableAccountId:string; readonly partyId:string; readonly partyRole:"company"|"agent"; readonly name:string; readonly currency:string; readonly amountMinor:string; readonly exposureMinor:string; readonly creditLimitMinor:string|null; readonly projectedExposureMinor:string; readonly requiresApproval:boolean; }
export interface ReceivableTarget { readonly accountId:string; readonly partyId:string; readonly partyRole:"company"|"agent"; readonly name:string; readonly currency:string; readonly creditLimitMinor:string; }
export interface ReceivableTransferResult extends ReceivablePreview { readonly journalId:string; readonly approvalId:string|null; readonly replayed:boolean; }
export interface ReceivableApprovalResult extends Omit<ReceivablePreview,"requiresApproval"> { readonly approvalId:string; readonly status:"pending"|"approved"|"rejected"; readonly replayed:boolean; }
export interface ReceivableServiceOptions { readonly database:Database; readonly events:EventBus; readonly idempotency:PostgresIdempotency; readonly approvals?:ApprovalService; }
export class ReceivableValidationError extends Error { constructor(m:string){super(m);this.name="ReceivableValidationError";} }
export class ReceivableNotFoundError extends Error { constructor(m:string){super(m);this.name="ReceivableNotFoundError";} }
export class ReceivableConflictError extends Error { constructor(m:string){super(m);this.name="ReceivableConflictError";} }
function plain(v:unknown,n:string):asserts v is Record<string,unknown>{if(typeof v!=="object"||v===null||Array.isArray(v)||Object.getPrototypeOf(v)!==Object.prototype&&Object.getPrototypeOf(v)!==null||Object.getOwnPropertySymbols(v).length)throw new ReceivableValidationError(`${n} must be a plain object`);}
function keys(v:Record<string,unknown>,a:string[],n:string){const x=Object.keys(v).sort(),y=[...a].sort();if(x.length!==y.length||x.some((k,i)=>k!==y[i]))throw new ReceivableValidationError(`${n} shape is invalid`);}
function keysWithOptional(v:Record<string,unknown>,required:string[],optional:string[],n:string){const actual=Object.keys(v);if(actual.some(key=>!required.includes(key)&&!optional.includes(key))||required.some(key=>!Object.hasOwn(v,key)))throw new ReceivableValidationError(`${n} shape is invalid`);}
function uuid(v:unknown,n:string){if(typeof v!=="string"||!UUID.test(v))throw new ReceivableValidationError(`${n} must be a lowercase UUID`);return v;}
function env(v:unknown,t:string,op:string):AuditEnvelope{plain(v,"envelope");keys(v,["actorId","tenantId","propertyNode","requestId","operation"],"envelope");if(uuid(v.tenantId,"envelope.tenantId")!==t||v.operation!==op)throw new ReceivableValidationError("audit envelope is invalid");return Object.freeze({actorId:uuid(v.actorId,"envelope.actorId"),tenantId:t,propertyNode:uuid(v.propertyNode,"envelope.propertyNode"),requestId:uuid(v.requestId,"envelope.requestId"),operation:op});}
function integer(v:unknown,n:string){if(typeof v!=="string"||!MONEY.test(v))throw new ReceivableConflictError(`${n} must be an exact integer`);return v;}
function error(e:unknown):never{const s=(e as {errno?:string;code?:string}).errno??(e as {code?:string}).code;if(s==="55000"||s==="23505")throw new ReceivableConflictError("Receivable transfer state is unavailable or stale");if(s==="42501")throw new ReceivableNotFoundError("Receivable target was not found in the property");if(s==="22023"||s==="22003")throw new ReceivableValidationError("Receivable transfer input is invalid");throw e;}
interface Row { folio_id:string; account_id:string; party_id:string; party_role:string; name:string; currency:string; amount_minor:string; exposure_minor:string; credit_limit_minor:string|null; }
interface TargetRow { account_id:string; party_id:string; party_role:string; name:string; currency:string; credit_limit_minor:string; }
interface CapRow extends Row { journal_id:string; business_date:string; guest_account_id:string; receivable_account_id:string; receivable_party_id:string; receivable_party_role:string; exposure_before_minor:string; projected_exposure_minor:string; approval_request_id:string|null; }
export class ReceivableService {
 readonly #db:Database; readonly #events:EventBus; readonly #idem:PostgresIdempotency; readonly #approvals?:ApprovalService;
 constructor(o:ReceivableServiceOptions){this.#db=o.database;this.#events=o.events;this.#idem=o.idempotency;this.#approvals=o.approvals;}
 #approval(){if(!this.#approvals)throw new ReceivableConflictError("Receivable approval capability is unavailable");return this.#approvals;}
 async #preview(tx:Tx,i:ReceivablePreviewInput):Promise<ReceivablePreview>{
  const r=(await tx<Row[]>`SELECT folio.id folio_id, target.id account_id, target.party_id party_id, role.party_role, party.display_name name, target.currency::text currency, COALESCE(balance.balance_minor,0)::text amount_minor, COALESCE(exposure.exposure_minor,'0'::text) exposure_minor, target.credit_limit_minor::text credit_limit_minor FROM folio JOIN account ON account.tenant_id=folio.tenant_id AND account.id=folio.account_id JOIN folio_balance balance ON balance.tenant_id=folio.tenant_id AND balance.folio_id=folio.id JOIN account target ON target.tenant_id=folio.tenant_id AND target.id=${i.receivableAccountId}::uuid JOIN party party ON party.tenant_id=target.tenant_id AND party.id=target.party_id AND party.status='active' JOIN LATERAL (SELECT party_role.role AS party_role FROM party_role WHERE party_role.tenant_id=target.tenant_id AND party_role.party_id=target.party_id AND party_role.role IN ('company','agent') ORDER BY CASE party_role.role WHEN 'company' THEN 0 ELSE 1 END LIMIT 1) role ON true LEFT JOIN LATERAL (SELECT COALESCE(sum(amount_minor),0)::text exposure_minor FROM posting_line WHERE tenant_id=target.tenant_id AND account_id=target.id) exposure ON true WHERE folio.tenant_id=${i.tenantId}::uuid AND folio.tenant_id=current_setting('app.tenant_id',true)::uuid AND folio.id=${i.folioId}::uuid AND folio.status='open' AND account.role='guest' AND account.status='open' AND account.property_node=${i.propertyNode}::uuid AND target.role='company' AND target.status='open' AND target.property_node=account.property_node AND target.currency=account.currency`)[0];
  if(!r||!UUID.test(r.party_id)||!CURRENCY.test(r.currency)||(r.party_role!=="company"&&r.party_role!=="agent"))throw new ReceivableNotFoundError("Receivable target is not canonical"); const a=integer(r.amount_minor,"amount"),e=integer(r.exposure_minor,"exposure"); if(BigInt(a)<=0n||r.credit_limit_minor===null)throw new ReceivableConflictError("Receivable transfer requires a positive balance and explicit credit limit"); const l=integer(r.credit_limit_minor,"limit"),p=(BigInt(e)+BigInt(a)).toString(); return Object.freeze({folioId:r.folio_id,receivableAccountId:i.receivableAccountId,partyId:r.party_id,partyRole:r.party_role,name:r.name,currency:r.currency,amountMinor:a,exposureMinor:e,creditLimitMinor:l,projectedExposureMinor:p,requiresApproval:BigInt(p)>BigInt(l)});
 }
 async preview(i:ReceivablePreviewInput){plain(i,"preview");keys(i,["tenantId","propertyNode","folioId","receivableAccountId"],"preview");const n={tenantId:uuid(i.tenantId,"tenantId"),propertyNode:uuid(i.propertyNode,"propertyNode"),folioId:uuid(i.folioId,"folioId"),receivableAccountId:uuid(i.receivableAccountId,"receivableAccountId")};return this.#db.withTenantTransaction(n.tenantId,t=>this.#preview(t,n));}
 async listTargets(input:ReceivableTargetListInput):Promise<readonly ReceivableTarget[]>{plain(input,"target list");keys(input,["tenantId","propertyNode"],"target list");const tenantId=uuid(input.tenantId,"tenantId"),propertyNode=uuid(input.propertyNode,"propertyNode");const rows=await this.#db.withTenantTransaction(tenantId,tx=>tx<TargetRow[]>`SELECT target.id account_id,target.party_id party_id,role.party_role,party.display_name name,target.currency::text currency,target.credit_limit_minor::text credit_limit_minor FROM account target JOIN party ON party.tenant_id=target.tenant_id AND party.id=target.party_id AND party.status='active' JOIN LATERAL (SELECT party_role.role AS party_role FROM party_role WHERE party_role.tenant_id=target.tenant_id AND party_role.party_id=target.party_id AND party_role.role IN ('company','agent') ORDER BY CASE party_role.role WHEN 'company' THEN 0 ELSE 1 END LIMIT 1) role ON true JOIN org_node property ON property.tenant_id=target.tenant_id AND property.id=target.property_node AND property.kind='property' WHERE target.tenant_id=${tenantId}::uuid AND target.tenant_id=current_setting('app.tenant_id',true)::uuid AND target.property_node=${propertyNode}::uuid AND target.role='company' AND target.status='open' AND target.credit_limit_minor IS NOT NULL AND target.credit_limit_minor>=0 ORDER BY party.display_name ASC,target.id ASC`);return Object.freeze(rows.map(row=>{if(!UUID.test(row.account_id)||!UUID.test(row.party_id)||(row.party_role!=="company"&&row.party_role!=="agent")||typeof row.name!=="string"||!CURRENCY.test(row.currency))throw new ReceivableConflictError("Receivable target is not canonical");return Object.freeze({accountId:row.account_id,partyId:row.party_id,partyRole:row.party_role,name:row.name,currency:row.currency,creditLimitMinor:integer(row.credit_limit_minor,"limit")});}));}
 async requestOverLimitApproval(input:RequestReceivableApprovalInput):Promise<ReceivableApprovalResult>{plain(input,"approval request");keys(input,["tenantId","folioId","receivableAccountId","idempotencyKey","envelope"],"approval request");const tenantId=uuid(input.tenantId,"tenantId"),folioId=uuid(input.folioId,"folioId"),accountId=uuid(input.receivableAccountId,"receivableAccountId");if(typeof input.idempotencyKey!=="string"||!KEY.test(input.idempotencyKey))throw new ReceivableValidationError("idempotencyKey is invalid");const envelope=env(input.envelope,tenantId,"approval.requested"),approvals=this.#approval();try{const out=await this.#db.withTenantTransaction(tenantId,tx=>this.#idem.execute<Record<string,JsonValue>>(tx,{tenantId,operation:"financials.receivable.approval.request",key:input.idempotencyKey,request:{actorId:envelope.actorId,propertyNode:envelope.propertyNode,folioId,accountId}},async q=>{const p=await this.#preview(q,{tenantId,propertyNode:envelope.propertyNode,folioId,receivableAccountId:accountId});if(!p.requiresApproval)throw new ReceivableConflictError("Within-limit receivable transfer requires no approval");const a=await approvals.request(q,{kind:"receivable_transfer_over_limit",subjectType:"folio",subjectId:folioId,requestedBy:envelope.actorId,payload:{partyId:p.partyId,accountId,folioId,amountMinor:p.amountMinor,exposureBeforeMinor:p.exposureMinor,creditLimitMinor:p.creditLimitMinor!,projectedExposureMinor:p.projectedExposureMinor},envelope});return {status:201,body:{approvalId:a.id,folioId,receivableAccountId:accountId,partyId:p.partyId,partyRole:p.partyRole,name:p.name,currency:p.currency,amountMinor:p.amountMinor,exposureMinor:p.exposureMinor,creditLimitMinor:p.creditLimitMinor,projectedExposureMinor:p.projectedExposureMinor,status:"pending" as const}};}));return {...out.body,replayed:out.replayed} as ReceivableApprovalResult;}catch(e){return error(e);}}
 async approveOverLimit(input:DecideReceivableApprovalInput):Promise<ReceivableApprovalResult>{return this.#decide(input,"approved");}
 async rejectOverLimit(input:DecideReceivableApprovalInput):Promise<ReceivableApprovalResult>{return this.#decide(input,"rejected");}
 async #decide(input:DecideReceivableApprovalInput,decision:"approved"|"rejected"):Promise<ReceivableApprovalResult>{plain(input,"approval decision");keys(input,["tenantId","folioId","approvalId","idempotencyKey","envelope"],"approval decision");const tenantId=uuid(input.tenantId,"tenantId"),folioId=uuid(input.folioId,"folioId"),approvalId=uuid(input.approvalId,"approvalId");if(typeof input.idempotencyKey!=="string"||!KEY.test(input.idempotencyKey))throw new ReceivableValidationError("idempotencyKey is invalid");const envelope=env(input.envelope,tenantId,"approval.decided"),approvals=this.#approval();try{const out=await this.#db.withTenantTransaction(tenantId,tx=>this.#idem.execute<Record<string,JsonValue>>(tx,{tenantId,operation:`financials.receivable.approval.${decision}`,key:input.idempotencyKey,request:{actorId:envelope.actorId,propertyNode:envelope.propertyNode,folioId,approvalId}},async q=>{const row=(await q<Array<{requested_by:string;payload:Record<string,unknown>}>>`SELECT requested_by,payload FROM approval_request WHERE tenant_id=${tenantId}::uuid AND id=${approvalId}::uuid AND kind='receivable_transfer_over_limit' AND subject_type='folio' AND subject_id=${folioId}::uuid AND status='pending'`)[0];if(!row||row.requested_by===envelope.actorId)throw new ReceivableConflictError("Receivable approval is unavailable");plain(row.payload,"approval payload");keys(row.payload,["partyId","accountId","folioId","amountMinor","exposureBeforeMinor","creditLimitMinor","projectedExposureMinor"],"approval payload");const accountId=uuid(row.payload.accountId,"approval accountId"),p=await this.#preview(q,{tenantId,propertyNode:envelope.propertyNode,folioId,receivableAccountId:accountId});if(!p.requiresApproval||row.payload.partyId!==p.partyId||row.payload.folioId!==folioId||row.payload.amountMinor!==p.amountMinor||row.payload.exposureBeforeMinor!==p.exposureMinor||row.payload.creditLimitMinor!==p.creditLimitMinor||row.payload.projectedExposureMinor!==p.projectedExposureMinor)throw new ReceivableConflictError("Receivable approval evidence is stale");const a=await approvals.decide(q,{approvalId,decision,decidedBy:envelope.actorId,envelope});return {status:200,body:{approvalId:a.id,folioId,receivableAccountId:accountId,partyId:p.partyId,partyRole:p.partyRole,name:p.name,currency:p.currency,amountMinor:p.amountMinor,exposureMinor:p.exposureMinor,creditLimitMinor:p.creditLimitMinor,projectedExposureMinor:p.projectedExposureMinor,status:decision}};}));return {...out.body,replayed:out.replayed} as ReceivableApprovalResult;}catch(e){return error(e);}}
 async transfer(input:ReceivableTransferInput):Promise<ReceivableTransferResult>{plain(input,"transfer");keysWithOptional(input,["tenantId","folioId","receivableAccountId","reason","idempotencyKey","envelope"],["approvalId"],"transfer");const t=uuid(input.tenantId,"tenantId"),f=uuid(input.folioId,"folioId"),a=uuid(input.receivableAccountId,"receivableAccountId"),approval=input.approvalId===undefined||input.approvalId===null?null:uuid(input.approvalId,"approvalId");if(typeof input.reason!=="string"||input.reason.trim()!==input.reason||new TextEncoder().encode(input.reason).length<1||new TextEncoder().encode(input.reason).length>500||/[\x00-\x1f\x7f\u200b-\u200d\u202a-\u202e\u2060\u2066-\u2069\ufeff]/u.test(input.reason)||typeof input.idempotencyKey!=="string"||!KEY.test(input.idempotencyKey))throw new ReceivableValidationError("transfer input is invalid");const en=env(input.envelope,t,"journal.posted");try{const out=await this.#db.withTenantTransaction(t,tx=>this.#idem.execute<Record<string,JsonValue>>(tx,{tenantId:t,operation:"financials.receivable.transfer",key:input.idempotencyKey,request:{actorId:en.actorId,propertyNode:en.propertyNode,folioId:f,receivableAccountId:a,approvalId:approval,reason:input.reason}},async q=>{const rows=await q<CapRow[]>`SELECT journal_id,business_date::text,currency::text,folio_id,guest_account_id,receivable_account_id,receivable_party_id,receivable_party_role,amount_minor::text,exposure_before_minor::text,credit_limit_minor::text,projected_exposure_minor::text,approval_request_id FROM public.create_receivable_transfer(${t}::uuid,${en.propertyNode}::uuid,${f}::uuid,${a}::uuid,${en.actorId}::uuid,${approval}::uuid,${input.reason})`;const r=rows[0];if(rows.length!==1||!r||!UUID.test(r.journal_id))throw new ReceivableConflictError("transfer capability returned invalid evidence");const p={folio_id:r.folio_id,receivable_account_id:r.receivable_account_id,amount_minor:integer(r.amount_minor,"amount"),approval_request_id:r.approval_request_id};const fact=await recordFact(q,{entityType:"journal",entityId:r.journal_id,envelope:en,payload:p});await this.#events.publish(q,{tenantId:t,propertyNode:en.propertyNode,businessDate:fact.businessDate,aggregateType:"journal",aggregateId:r.journal_id,eventType:"journal.posted",actorId:en.actorId,correlationId:en.requestId,payload:p});return {status:201,body:{journalId:r.journal_id,folioId:r.folio_id,receivableAccountId:r.receivable_account_id,partyId:r.receivable_party_id,partyRole:r.receivable_party_role,name:"",currency:r.currency,amountMinor:r.amount_minor,exposureMinor:r.exposure_before_minor,creditLimitMinor:r.credit_limit_minor,projectedExposureMinor:r.projected_exposure_minor,requiresApproval:approval!==null,approvalId:r.approval_request_id}};}));return {...out.body,replayed:out.replayed} as ReceivableTransferResult;}catch(e){return error(e);}}
}
