import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { SQL } from "bun";
import { TrustAccountingService, TrustAccountingValidationError } from "../src/contexts/financials";
import { Database, PostgresEventBus, PostgresIdempotency, type EventBus, type Tx } from "../src/kernel";

const T="00000000-0000-0000-0000-000000034401",P="00000000-0000-0000-0000-000000034411";
const MAKER="00000000-0000-0000-0000-000000034421",CHECKER="00000000-0000-0000-0000-000000034422";
const OWNER="00000000-0000-0000-0000-000000034431",TRUST="00000000-0000-0000-0000-000000034441",PAYABLE="00000000-0000-0000-0000-000000034442";
const ROLE_M="00000000-0000-0000-0000-000000034451",ROLE_C="00000000-0000-0000-0000-000000034452";
const DEPLOY=process.env.YELLOW_DEPLOY_DATABASE_URL;
const RUNTIME=process.env.YELLOW_OWNER_TRUST_DATABASE_URL??process.env.YELLOW_RUNTIME_DATABASE_URL;

describe("Order 344 owner-trust guard intentional red", () => {
  test("exports the governed owner-trust command", () => {
    expect(TrustAccountingService).toBeFunction();
  });

  test("rejects noncanonical exact-money and caller authority", async () => {
    const service=new TrustAccountingService({events:undefined as unknown as EventBus,idempotency:undefined as unknown as PostgresIdempotency});
    const envelope={tenantId:T,propertyNode:P,actorId:MAKER,requestId:crypto.randomUUID(),operation:"journal.posted"};
    for(const amountMinor of ["0","-1","01","9223372036854775808"]){
      await expect(service.postOwnerExpense(undefined as unknown as Tx,{tenantId:T,trustAccountId:TRUST,amountMinor,reason:"Owner expense",idempotencyKey:"order344-boundary",envelope})).rejects.toBeInstanceOf(TrustAccountingValidationError);
    }
    await expect(service.postOwnerExpense(undefined as unknown as Tx,{tenantId:T,trustAccountId:TRUST,amountMinor:"1",reason:"Owner expense",idempotencyKey:"order344-boundary",envelope,balanceBeforeMinor:"100"} as never)).rejects.toBeInstanceOf(TrustAccountingValidationError);
  });
});

const databaseDescribe=DEPLOY&&RUNTIME?describe.serial:describe.skip;
let deploy:SQL|undefined,runtime:SQL|undefined,eventPool:SQL|undefined,database:Database|undefined,businessDate="";
async function state(op:()=>Promise<unknown>,expected:string){try{await op();}catch(e){expect((e as {errno?:string}).errno).toBe(expected);return;}throw new Error(`expected ${expected}`);}
async function cap(amount:string,approval:string|null=null,reason="Owner expense"){return runtime!.begin(async tx=>{await tx`SELECT set_config('app.tenant_id',${T},true)`;await tx.unsafe("SET LOCAL ROLE app_role");return tx<Array<{journal_id:string;available_before_minor:string|bigint;projected_available_minor:string|bigint;approval_request_id:string|null}>>`SELECT * FROM public.create_owner_trust_expense(${T}::uuid,${TRUST}::uuid,${MAKER}::uuid,${approval}::uuid,${amount}::bigint,${reason})`;});}
databaseDescribe("Order 344 fresh PostgreSQL owner-trust proof",()=>{
  beforeAll(async()=>{
    deploy=new SQL(DEPLOY!);runtime=new SQL(RUNTIME!);eventPool=new SQL(RUNTIME!);database=Database.connect(RUNTIME!);businessDate=(await deploy<{d:string}[]>`SELECT (transaction_timestamp() AT TIME ZONE 'UTC')::date::text d`)[0]!.d;
    await deploy`INSERT INTO tenant(id,slug,name,tier,status) VALUES(${T}::uuid,'order344','Order 344','shared','active')`;
    await deploy`INSERT INTO org_node(id,tenant_id,path,kind,name,timezone,currency) VALUES(${P}::uuid,${T}::uuid,'order344','property','Order 344','UTC','USD')`;
    await deploy`INSERT INTO app_user(id,tenant_id,email,display_name,status) VALUES(${MAKER}::uuid,${T}::uuid,'maker@order344.test','Maker','active'),(${CHECKER}::uuid,${T}::uuid,'checker@order344.test','Checker','active')`;
    await deploy`INSERT INTO permission(code,description) VALUES('financials.trust:post','Post owner trust expense'),('financials.trust:approve-negative','Approve negative owner trust') ON CONFLICT DO NOTHING`;
    await deploy`INSERT INTO role(id,tenant_id,name) VALUES(${ROLE_M}::uuid,${T}::uuid,'trust maker'),(${ROLE_C}::uuid,${T}::uuid,'trust checker')`;
    await deploy`INSERT INTO role_permission(role_id,permission_code) VALUES(${ROLE_M}::uuid,'financials.trust:post'),(${ROLE_C}::uuid,'financials.trust:approve-negative')`;
    await deploy`INSERT INTO user_role(tenant_id,user_id,role_id,scope_node) VALUES(${T}::uuid,${MAKER}::uuid,${ROLE_M}::uuid,${P}::uuid),(${T}::uuid,${CHECKER}::uuid,${ROLE_C}::uuid,${P}::uuid)`;
    await deploy`INSERT INTO party(id,tenant_id,kind,display_name,status) VALUES(${OWNER}::uuid,${T}::uuid,'person','Order 344 Owner','active')`;
    await deploy`INSERT INTO party_role(tenant_id,party_id,role) VALUES(${T}::uuid,${OWNER}::uuid,'owner')`;
    await deploy`INSERT INTO account(id,tenant_id,property_node,role,party_id,name,currency,status) VALUES(${TRUST}::uuid,${T}::uuid,${P}::uuid,'trust',${OWNER}::uuid,'Owner trust','USD','open'),(${PAYABLE}::uuid,${T}::uuid,${P}::uuid,'payable',NULL,'Owner payable','USD','open')`;
    await deploy`INSERT INTO tx_code_route(tenant_id,property_node,currency,tx_code,debit_account_id,credit_account_id) VALUES(${T}::uuid,${P}::uuid,'USD','OWNER_TRUST_EXPENSE',${TRUST}::uuid,${PAYABLE}::uuid)`;
    await deploy`INSERT INTO business_day(tenant_id,property_node,business_date) VALUES(${T}::uuid,${P}::uuid,${businessDate}::date)`;
    await deploy.begin(async tx=>{const rows=await tx<{id:string}[]>`INSERT INTO journal(tenant_id,property_node,business_date,kind,description,currency,source,created_by) VALUES(${T}::uuid,${P}::uuid,${businessDate}::date,'paidout','Opening owner funds','USD','{}',${MAKER}::uuid) RETURNING id`;const j=rows[0]!.id;await tx`INSERT INTO posting_line(tenant_id,journal_id,seq,account_id,tx_code,amount_minor,business_date,currency) VALUES(${T}::uuid,${j}::uuid,1,${TRUST}::uuid,'OWNER_TRUST_EXPENSE',-10000,${businessDate}::date,'USD'),(${T}::uuid,${j}::uuid,2,${PAYABLE}::uuid,'OWNER_TRUST_EXPENSE',10000,${businessDate}::date,'USD')`;});
  },30000);
  afterAll(async()=>{await database?.close();await eventPool?.close({timeout:0});await runtime?.close({timeout:0});await deploy?.close({timeout:0});});
  test("P1 exact catalogue and raw mutation authority",async()=>{const rows=await deploy!`SELECT (SELECT count(*)::int FROM pg_tables WHERE schemaname='public') tables,(SELECT count(*)::int FROM pg_policies WHERE schemaname='public') policies,has_table_privilege('app_role','trust_negative_authorization','INSERT') insert_ok,has_table_privilege('app_role','trust_negative_authorization','SELECT') select_ok`;expect(rows).toEqual([{tables:111,policies:101,insert_ok:false,select_ok:true}]);await state(()=>runtime!`SELECT * FROM public.create_owner_trust_expense(${T}::uuid,${TRUST}::uuid,${MAKER}::uuid,NULL,1,'raw')`,'42501');});
  test("P2 derives credit-normal availability and exact negative approval",async()=>{const first=(await cap("4000"))[0]!;expect([String(first.available_before_minor),String(first.projected_available_minor),first.approval_request_id]).toEqual(["10000","6000",null]);await state(()=>cap("7000"),'55000');const approval=crypto.randomUUID();const payload={ownerPartyId:OWNER,trustAccountId:TRUST,payableAccountId:PAYABLE,amountMinor:"7000",availableBeforeMinor:"6000",projectedAvailableMinor:"-1000",reason:"Owner expense"};await deploy!`INSERT INTO approval_request(id,tenant_id,kind,subject_type,subject_id,requested_by,payload,status,decided_by,decided_at) VALUES(${approval}::uuid,${T}::uuid,'owner_trust_negative_expense','account',${TRUST}::uuid,${MAKER}::uuid,${payload}::jsonb,'approved',${CHECKER}::uuid,transaction_timestamp())`;const posted=(await cap("7000",approval))[0]!;expect([String(posted.available_before_minor),String(posted.projected_available_minor),posted.approval_request_id]).toEqual(["6000","-1000",approval]);await state(()=>cap("1",approval),'55000');expect(await deploy!<Array<{amount_minor:string;available_before_minor:string;projected_available_minor:string}>>`SELECT amount_minor::text,available_before_minor::text,projected_available_minor::text FROM trust_negative_authorization WHERE tenant_id=${T}::uuid`).toEqual([{amount_minor:"7000",available_before_minor:"6000",projected_available_minor:"-1000"}]);});
  test("P3 service replay is one journal/fact and two events; changed content conflicts",async()=>{const approval=crypto.randomUUID(),reason="Replay-safe owner expense";const payload={ownerPartyId:OWNER,trustAccountId:TRUST,payableAccountId:PAYABLE,amountMinor:"1",availableBeforeMinor:"-1000",projectedAvailableMinor:"-1001",reason};await deploy!`INSERT INTO approval_request(id,tenant_id,kind,subject_type,subject_id,requested_by,payload,status,decided_by,decided_at) VALUES(${approval}::uuid,${T}::uuid,'owner_trust_negative_expense','account',${TRUST}::uuid,${MAKER}::uuid,${payload}::jsonb,'approved',${CHECKER}::uuid,transaction_timestamp())`;const service=new TrustAccountingService({events:new PostgresEventBus(eventPool!),idempotency:new PostgresIdempotency()});const input={tenantId:T,trustAccountId:TRUST,amountMinor:"1",reason,approvalRequestId:approval,idempotencyKey:"order344-service-replay",envelope:{tenantId:T,propertyNode:P,actorId:MAKER,requestId:crypto.randomUUID(),operation:"journal.posted"}} as const;const first=await database!.withTenantTransaction(T,tx=>service.postOwnerExpense(tx,input));const replay=await database!.withTenantTransaction(T,tx=>service.postOwnerExpense(tx,input));expect([first.replayed,replay.replayed,replay.journalId]).toEqual([false,true,first.journalId]);await expect(database!.withTenantTransaction(T,tx=>service.postOwnerExpense(tx,{...input,reason:"Changed reason"}))).rejects.toThrow(/Idempotency key/);expect(await deploy!<Array<{facts:number;events:number;keys:number}>>`SELECT (SELECT count(*)::int FROM fact_log WHERE tenant_id=${T}::uuid AND entity_id=${first.journalId}::uuid) facts,(SELECT count(*)::int FROM outbox WHERE tenant_id=${T}::uuid AND correlation_id=${input.envelope.requestId}::uuid) events,(SELECT count(*)::int FROM api_idempotency WHERE tenant_id=${T}::uuid AND operation='financials.trust.owner-expense.post') keys`).toEqual([{facts:1,events:2,keys:1}]);});
  test("P4 late event failure rolls every artifact back and permits clean retry",async()=>{const approval=crypto.randomUUID(),reason="Rollback owner expense";const payload={ownerPartyId:OWNER,trustAccountId:TRUST,payableAccountId:PAYABLE,amountMinor:"1",availableBeforeMinor:"-1001",projectedAvailableMinor:"-1002",reason};await deploy!`INSERT INTO approval_request(id,tenant_id,kind,subject_type,subject_id,requested_by,payload,status,decided_by,decided_at) VALUES(${approval}::uuid,${T}::uuid,'owner_trust_negative_expense','account',${TRUST}::uuid,${MAKER}::uuid,${payload}::jsonb,'approved',${CHECKER}::uuid,transaction_timestamp())`;const input={tenantId:T,trustAccountId:TRUST,amountMinor:"1",reason,approvalRequestId:approval,idempotencyKey:"order344-service-rollback",envelope:{tenantId:T,propertyNode:P,actorId:MAKER,requestId:crypto.randomUUID(),operation:"journal.posted"}} as const;const failing=new TrustAccountingService({events:{publish:async()=>{throw new Error("injected order344 late failure");}} as unknown as EventBus,idempotency:new PostgresIdempotency()});await expect(database!.withTenantTransaction(T,tx=>failing.postOwnerExpense(tx,input))).rejects.toThrow("injected order344");expect(await deploy!<Array<{journals:number;authorizations:number;facts:number;events:number;keys:number}>>`SELECT (SELECT count(*)::int FROM journal WHERE tenant_id=${T}::uuid AND description=${reason}) journals,(SELECT count(*)::int FROM trust_negative_authorization WHERE tenant_id=${T}::uuid AND approval_request_id=${approval}::uuid) authorizations,(SELECT count(*)::int FROM fact_log WHERE tenant_id=${T}::uuid AND payload @> ${JSON.stringify({approvalRequestId:approval})}::text::jsonb) facts,(SELECT count(*)::int FROM outbox WHERE tenant_id=${T}::uuid AND correlation_id=${input.envelope.requestId}::uuid) events,(SELECT count(*)::int FROM api_idempotency WHERE tenant_id=${T}::uuid AND operation='financials.trust.owner-expense.post' AND key_hash=encode(digest(${input.idempotencyKey},'sha256'),'hex')) keys`).toEqual([{journals:0,authorizations:0,facts:0,events:0,keys:0}]);const good=new TrustAccountingService({events:new PostgresEventBus(eventPool!),idempotency:new PostgresIdempotency()});expect((await database!.withTenantTransaction(T,tx=>good.postOwnerExpense(tx,input))).replayed).toBeFalse();});
});
