import { expect, test } from "bun:test";
import { fileURLToPath } from "node:url";

test("Order429 mutation-sensitive proof rejects child and output authority mutations", () => {
  const sourceUrl = new URL("../src/contexts/tax-fiscal/india-irp-accommodation-source.ts", import.meta.url).href;
  const composerUrl = new URL("../src/contexts/tax-fiscal/india-irp-accommodation-validation-compatibility-pre-document-evidence-assembly.ts", import.meta.url).href;
  const targetUrl = new URL("../src/contexts/tax-fiscal/india-irp-accommodation-fiscal-action-readiness.ts", import.meta.url).href;
  const script = `
    import { mock } from "bun:test";
    const tenant = "10000000-0000-4000-8000-000000000001";
    const ids = { propertyNode:"b0000000-0000-4000-8000-00000000000b", reservationId:"80000000-0000-4000-8000-000000000008", folioId:"90000000-0000-4000-8000-000000000009", journalId:"40000000-0000-4000-8000-000000000004", recipientPartyId:"a0000000-0000-4000-8000-00000000000a", recipientRegistrationId:"c0000000-0000-4000-8000-00000000000c", classificationId:"e0000000-0000-4000-8000-00000000000e" };
    const h = "a".repeat(64), digest = (v) => new Bun.CryptoHasher("sha256").update(JSON.stringify(v)).digest("hex");
    const fr = (v) => { if (v && typeof v === "object" && !Object.isFrozen(v)) { for (const c of Object.values(v)) fr(c); Object.freeze(v); } return v; };
    const bind = (tenantId, body, key) => { const { [key]: _, ...rest } = body; return fr({ ...body, [key]: digest({ tenantId, ...rest }) }); };
    const input = fr({ tenantId:tenant, ...ids, supplyNatureAtTimeOfSupplyInput:fr({}), supplyNatureAtTimeOfSupplyResult:fr({ evidenceHash:h }) });
    const makeSource = () => {
      const financialBody = { state:"eligible_current_posted_source", postingBindingId:"f0000000-0000-4000-8000-00000000000f", journalId:ids.journalId, taxId:"11000000-0000-4000-8000-000000000011", taxGeneration:1, taxEvidenceHash:h, valuationId:"12000000-0000-4000-8000-000000000012", valuationGeneration:1, finalValuationEvidenceHash:h, applicabilityId:"13000000-0000-4000-8000-000000000013", applicabilityEvidenceHash:h, reservationId:ids.reservationId, folioId:ids.folioId, guestAccountId:"14000000-0000-4000-8000-000000000014", propertyNode:ids.propertyNode, businessDate:"2044-01-01", currency:"INR", transactionValueMinor:"10000", taxMinor:"500", grandTotalMinor:"10500", componentFamily:"igst", predecessorHashes:{section14:h,levyComponentIdentity:h,reservationLineage:h,attributionSnapshot:h}, roomNights:[{ordinal:"0"}], components:[], journalLines:[] };
      const financial = bind(tenant, financialBody, "sourceEvidenceHash");
      const body = { state:"eligible_irp_invoice_source", financialSource:financial, legalBuyerPartyId:ids.recipientPartyId, sellerRegistration:{registrationId:"d0000000-0000-4000-8000-00000000000d",evidenceHash:h}, recipientRegistration:{registrationId:ids.recipientRegistrationId,evidenceHash:h}, sellerDetails:{lineage:{registrationId:"d0000000-0000-4000-8000-00000000000d",evidenceHash:h}}, buyerDetails:{lineage:{partyId:ids.recipientPartyId,registrationId:ids.recipientRegistrationId,evidenceHash:h}}, placeOfSupply:{candidateHash:h}, classification:{evidenceHash:h}, supplyNatureAtTimeOfSupply:{evidenceHash:h,propertyNode:ids.propertyNode,reservationId:ids.reservationId,folioId:ids.folioId,recipientPartyId:ids.recipientPartyId,recipientRegistrationId:ids.recipientRegistrationId,supplierRegistrationId:"d0000000-0000-4000-8000-00000000000d"}, componentFamily:{evidenceHash:h,propertyNode:ids.propertyNode,reservationId:ids.reservationId,folioId:ids.folioId,supplierRegistrationId:"d0000000-0000-4000-8000-00000000000d",componentFamily:"igst"} };
      return bind(tenant, body, "evidenceHash");
    };
    const makePre = (source) => { const body = { state:"incomplete_non_submit_ready_irp_accommodation_validation_compatibility_pre_document_evidence", format:"irp_json_1_1", submissionReady:false, authenticatedProviderSandboxCertified:false, explicitlyExcludedEvidence:["DocDtls"], sections:{Version:"1.1",TranDtls:{TaxSch:"GST",SupTyp:"B2B"},SellerDtls:{},BuyerDtls:{},ItemList:[{Qty:"1.000",Unit:"OTH"}],ValDtls:{}}, sectionsJson:"", lineage:{sourceEvidenceHash:source.evidenceHash,preDocumentEvidenceAssemblyHash:h,serviceQuantityUqcCompatibilityEvidenceHash:h,itemCandidatesEvidenceHash:h}, sourceEvidenceHash:source.evidenceHash }; body.sectionsJson=JSON.stringify(body.sections); return bind(tenant,body,"evidenceHash"); };
    class SourceValidation extends Error {} class SourceNotFound extends Error {} class SourceConflict extends Error {};
    let sourceMode="ok", preMode="ok";
    mock.module(${JSON.stringify(sourceUrl)}, () => ({ IndiaIrpAccommodationSourceValidationError:SourceValidation, IndiaIrpAccommodationSourceNotFoundError:SourceNotFound, IndiaIrpAccommodationSourceConflictError:SourceConflict, IndiaIrpAccommodationSourceService:class { async resolve() { if(sourceMode==="not-found") throw new SourceNotFound("source absent"); if(sourceMode==="conflict") throw new SourceConflict("source conflict"); const source=makeSource(); return sourceMode==="hash" ? fr({...source,evidenceHash:"b".repeat(64)}) : source; } } }));
    mock.module(${JSON.stringify(composerUrl)}, () => ({ composeIndiaIrpAccommodationValidationCompatibilityPreDocumentEvidenceAssembly:({source}) => { const pre=makePre(source); if(preMode==="state") return fr({...pre,state:"tampered"}); if(preMode==="hash") return fr({...pre,evidenceHash:"b".repeat(64)}); if(preMode==="doc") return fr({...pre,sections:{...pre.sections,DocDtls:{No:"1"}}}); return pre; } }));
    const { IndiaIrpAccommodationFiscalActionReadinessService, IndiaIrpAccommodationFiscalActionReadinessNotFoundError, IndiaIrpAccommodationFiscalActionReadinessConflictError } = await import(${JSON.stringify(targetUrl)}+"?order429-hostile");
    const service = new IndiaIrpAccommodationFiscalActionReadinessService(), tx = async () => [];
    const baseline = await service.resolve(tx, input); if(baseline.state!=="blocked_pending_fiscal_document_origin_policy" || baseline.submissionReady!==false || baseline.permittedActions.length!==0 || JSON.stringify(baseline.blockers)!==JSON.stringify(["FISCAL_DOCUMENT_ORIGIN_UNSELECTED","LEGAL_DOCUMENT_NUMBER_FORMAT_UNCONFIGURED","DOCUMENT_SERIES_UNBOUND"]) || JSON.stringify(baseline).includes(tenant) || !Object.isFrozen(baseline) || JSON.stringify(await service.resolve(tx,input))!==JSON.stringify(baseline)) process.exit(10);
    for (const m of ["hash"]) { sourceMode=m; try { await service.resolve(tx,input); process.exit(11); } catch (e) { if(e.name!=="IndiaIrpAccommodationFiscalActionReadinessConflictError") process.exit(12); } sourceMode="ok"; }
    for (const m of ["state","hash","doc"]) { preMode=m; try { await service.resolve(tx,input); process.exit(13); } catch (e) { if(e.name!=="IndiaIrpAccommodationFiscalActionReadinessConflictError") process.exit(14); } preMode="ok"; }
    sourceMode="not-found"; try { await service.resolve(tx,input); process.exit(15); } catch(e) { if(e.name!=="IndiaIrpAccommodationFiscalActionReadinessNotFoundError" || !(e instanceof IndiaIrpAccommodationFiscalActionReadinessNotFoundError)) process.exit(16); }
    sourceMode="conflict"; try { await service.resolve(tx,input); process.exit(17); } catch(e) { if(e.name!=="IndiaIrpAccommodationFiscalActionReadinessConflictError" || !(e instanceof IndiaIrpAccommodationFiscalActionReadinessConflictError)) process.exit(18); }
    process.exit(0);
  `;
  const result = Bun.spawnSync([Bun.which("bun") ?? process.execPath, "-e", script], { cwd: fileURLToPath(new URL("..", import.meta.url)), stdout: "pipe", stderr: "pipe" });
  if (result.exitCode !== 0) console.error(result.stdout.toString(), result.stderr.toString());
  expect(result.exitCode).toBe(0);
});
