import { describe, expect, test } from "bun:test";
import {
  IndiaGstRegistrationAtTimeOfSupplyConflictError,
  IndiaGstRegistrationAtTimeOfSupplyNotFoundError,
  IndiaGstRegistrationAtTimeOfSupplyService,
  IndiaGstRegistrationAtTimeOfSupplyValidationError,
} from "../src/contexts/tax-fiscal";
import { createPositiveTaxAttributionSnapshot } from "../src/contexts/tax-fiscal/attribution";
import type { Tx } from "../src/kernel";

const id = (n: number) => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
const TENANT = id(29501), PROPERTY = id(29502), RESERVATION = id(29503), REGISTRATION = id(29504), LOCATION = id(29505), STATUS = id(29506), SERVICE = id(29507), PAYMENT = id(29508), INVOICE = id(29509), LINEAGE = id(29510), HOLD = id(29511), ATTR = id(29512), SEGMENT = id(29513), EXTENSION = id(29514);
const QUOTE = "a".repeat(64), SERVICE_EVIDENCE = "b".repeat(64), PAYMENT_EVIDENCE = "c".repeat(64), INVOICE_EVIDENCE = "d".repeat(64), STATUS_EVIDENCE = "e".repeat(64), CONTENT = "f".repeat(64);
const hash = (value: unknown) => new Bun.CryptoHasher("sha256").update(JSON.stringify(value)).digest("hex");
const jurisdiction = { extensionId: EXTENSION, ownerTenantId: TENANT, key: "in.order295.gst.27", version: "7", contentHash: CONTENT };
const registrationBody = { registrationId: REGISTRATION, tenantId: TENANT, propertyNode: PROPERTY, scheme: "in-gstin", currency: "INR", jurisdiction, gstin: "27AAPFU0939F1ZV", stateCode: "27", legalName: "Yellow Order 295 Hotel Private Limited", tradeName: "Yellow Order 295 Hotel", addressLine: "1 Marine Drive", locality: "Mumbai", postalCode: "400001" };
const REGISTRATION_HASH = hash(registrationBody);
const locationBody = { tenantId: TENANT, supplierServiceLocationId: LOCATION, propertyNode: PROPERTY, jurisdiction, supplier: { registrationId: REGISTRATION, evidenceHash: REGISTRATION_HASH }, serviceScope: "lodging_accommodation", registeredPlace: { kind: "principal_place_of_business", stateCode: "27", addressLine: "1 Marine Drive", locality: "Mumbai", postalCode: "400001" }, locationBasis: "supply_made_from_registered_place_of_business", legalRule: "IGST_ACT_2_15_A" };
const LOCATION_HASH = hash(locationBody);
const STATUS_HASH = hash({ tenantId: TENANT, supplierGstRegistrationStatusId: STATUS, propertyNode: PROPERTY, supplierServiceLocation: { id: LOCATION, evidenceHash: LOCATION_HASH }, supplier: { registrationId: REGISTRATION, evidenceHash: REGISTRATION_HASH }, statusAsOf: "2043-06-15", gstRegistration: { status: "active", taxpayerType: "regular", source: "gst_common_portal", evidenceSha256: STATUS_EVIDENCE }, legalRule: "CGST_ACT_25_29_30_AND_RULE_21A_REGISTRATION_STATUS" });
const attribution = createPositiveTaxAttributionSnapshot({
  origin: { kind: "rate_quote", quoteHash: QUOTE }, currency: "INR",
  line: { lineId: "room", revenueGroup: "room_revenue", amountMinor: 10500n, nights: 1, personNights: 2, roomNights: [{ businessDate: "2043-06-01", amountMinor: 10500n }] },
  assignments: [{ businessDate: "2043-06-01", jurisdictionKey: "in.order295.gst.27", evidenceRef: `tax-assignment:${QUOTE}` }],
  jurisdiction: { extensionId: EXTENSION, ownerTenantId: TENANT, key: "in.order295.gst.27", version: 7, contentHash: CONTENT, evidenceRef: `tax-jurisdiction:${CONTENT}` },
  evaluation: { schemaVersion: 1, jurisdictionKey: "in.order295.gst.27", country: "IN", priceDisplay: "tax_exclusive", rounding: "line", inputTotalMinor: 10500n, baseTotalMinor: 10500n, taxTotalMinor: 0n, grandTotalMinor: 10500n, taxes: [{ code: "GST_ROOM", name: "GST", taxMinor: 0n, components: [{ lineId: "room", revenueGroup: "room_revenue", baseMinor: 10500n, taxMinor: 0n, rateBasisPoints: 0 }] }] },
});
const row = (overrides: Record<string, unknown> = {}): Record<string, unknown> => ({
  tenant_id: TENANT, registration_id: REGISTRATION, registration_property_node: PROPERTY, registration_scheme: "in-gstin", registration_currency: "INR", jurisdiction_extension_id: EXTENSION, jurisdiction_owner_tenant_id: TENANT, jurisdiction_key: jurisdiction.key, jurisdiction_version: jurisdiction.version, jurisdiction_content_hash: CONTENT, registration_number: registrationBody.gstin, region_code: "27", legal_name: registrationBody.legalName, trade_name: registrationBody.tradeName, address_line: registrationBody.addressLine, locality: registrationBody.locality, postal_code: registrationBody.postalCode,
  location_id: LOCATION, location_registration_id: REGISTRATION, location_supplier_evidence_hash: REGISTRATION_HASH, location_service_scope: "lodging_accommodation", registered_place_kind: "principal_place_of_business", location_basis: "supply_made_from_registered_place_of_business", location_legal_rule: "IGST_ACT_2_15_A", status_id: STATUS, status_registration_id: REGISTRATION, status_supplier_evidence_hash: REGISTRATION_HASH, status_as_of: "2043-06-15", gst_registration_status: "active", gst_taxpayer_type: "regular", gst_status_source: "gst_common_portal", gst_status_evidence_sha256: STATUS_EVIDENCE, status_legal_rule: "CGST_ACT_25_29_30_AND_RULE_21A_REGISTRATION_STATUS",
  service_id: SERVICE, payment_id: PAYMENT, invoice_id: INVOICE, property_node: PROPERTY, reservation_id: RESERVATION, service_date: "2043-06-01", payment_date: "2043-06-15", invoice_date: "2043-07-01", service_currency: "INR", payment_currency: "INR", invoice_currency: "INR", payment_amount: "10500", invoice_amount: "10500", service_evidence: SERVICE_EVIDENCE, payment_evidence: PAYMENT_EVIDENCE, invoice_evidence: INVOICE_EVIDENCE, books_date: "2043-06-15", bank_date: "2043-06-15", service_source: "governed_service_provision_record", service_rule: "CGST_ACT_13_2_B_SERVICE_PROVISION_DATE_INPUT_ONLY", payment_source: "governed_supplier_payment_receipt_record", payment_rule: "CGST_ACT_13_2_EXPLANATION_II_PAYMENT_RECEIPT_DATE_INPUT_ONLY", invoice_source: "governed_supplier_tax_invoice_record", invoice_rule: "CGST_ACT_13_2_INVOICE_DATE_INPUT_ONLY", coverage_scope: "full_attribution", invoice_series: "FY2043", invoice_serial: "000042", service_lineage_id: LINEAGE, service_hold_binding_id: HOLD, service_attribution_id: ATTR, service_segment_id: SEGMENT, service_quote_hash: QUOTE, service_snapshot_hash: attribution.snapshotHash, lineage_id: LINEAGE, lineage_property_node: PROPERTY, lineage_hold_binding_id: HOLD, lineage_attribution_id: ATTR, lineage_reservation_id: RESERVATION, lineage_segment_id: SEGMENT, lineage_quote_hash: QUOTE, lineage_snapshot_hash: attribution.snapshotHash, lineage_currency: "INR", attribution_snapshot: attribution, ...overrides,
});
const TOS_HASH = hash({ serviceProvisionSnapshotId: SERVICE, paymentReceiptSnapshotId: PAYMENT, invoiceIssueSnapshotId: INVOICE, propertyNode: PROPERTY, reservationId: RESERVATION, reservationLineage: { lineageId: LINEAGE, holdBindingId: HOLD, attributionId: ATTR, reservationId: RESERVATION, segmentId: SEGMENT, originQuoteHash: QUOTE, snapshotHash: attribution.snapshotHash, currency: "INR" }, attribution: { originKind: "rate_quote", lineId: "room", revenueGroup: "room_revenue" }, serviceProvisionDate: "2043-06-01", paymentReceiptDate: "2043-06-15", invoiceIssueDate: "2043-07-01", deadlineDate: "2043-07-01", candidateDates: { invoiceIssueDate: "2043-07-01", paymentReceiptDate: "2043-06-15" }, branch: "section13_2_a_invoice_or_payment", timeOfSupplyDate: "2043-06-15", regime: "ordinary_rule47_30_day", source: "governed_rule47_ordinary_regime_record", legalRule: "CGST_ACT_13_2_A_OR_B_ORDINARY_TIME_OF_SUPPLY", ordinaryRegimeEvidenceSha256: "1".repeat(64), invoiceSeries: "FY2043", invoiceSerial: "000042", supplierBooksEntryDate: "2043-06-15", supplierBankCreditDate: "2043-06-15", coverageScope: "full_attribution", serviceProvisionSource: "governed_service_provision_record", serviceProvisionLegalRule: "CGST_ACT_13_2_B_SERVICE_PROVISION_DATE_INPUT_ONLY", paymentReceiptSource: "governed_supplier_payment_receipt_record", paymentReceiptLegalRule: "CGST_ACT_13_2_EXPLANATION_II_PAYMENT_RECEIPT_DATE_INPUT_ONLY", invoiceIssueSource: "governed_supplier_tax_invoice_record", invoiceIssueLegalRule: "CGST_ACT_13_2_INVOICE_DATE_INPUT_ONLY", serviceProvisionEvidenceSha256: SERVICE_EVIDENCE, paymentReceiptEvidenceSha256: PAYMENT_EVIDENCE, invoiceIssueEvidenceSha256: INVOICE_EVIDENCE, amountMinor: "10500", currency: "INR" });
const input = (overrides: Record<string, unknown> = {}) => ({ tenantId: TENANT, propertyNode: PROPERTY, reservationId: RESERVATION, supplierServiceLocationId: LOCATION, supplierGstRegistrationStatusId: STATUS, serviceProvisionSnapshotId: SERVICE, paymentReceiptSnapshotId: PAYMENT, invoiceIssueSnapshotId: INVOICE, statusAsOf: "2043-06-15", timeOfSupplyDate: "2043-06-15", serviceProvisionDate: "2043-06-01", paymentReceiptDate: "2043-06-15", invoiceIssueDate: "2043-07-01", ordinaryRegimeSource: "governed_rule47_ordinary_regime_record", ordinaryRegimeEvidenceSha256: "1".repeat(64), supplierRegistrationStatusEvidenceHash: STATUS_HASH, timeOfSupplyEvidenceHash: TOS_HASH, ...overrides });
const tx = (rows: readonly Record<string, unknown>[], sql: string[] = []) => (async (strings: TemplateStringsArray) => { sql.push(strings.join("?")); return rows; }) as unknown as Tx;
const deeplyFrozen = (value: unknown, seen = new Set<object>()): void => { if (typeof value !== "object" || value === null || seen.has(value)) return; seen.add(value); expect(Object.isFrozen(value)).toBeTrue(); for (const key of Reflect.ownKeys(value)) deeplyFrozen((value as Record<PropertyKey, unknown>)[key], seen); };

describe("Order 295 GST registration at exact time of supply", () => {
  test("revalidates the complete chain in one read and returns frozen affirmative evidence", async () => {
    const statements: string[] = [], result = await new IndiaGstRegistrationAtTimeOfSupplyService().resolve(tx([row()], statements), input() as never);
    expect(statements).toHaveLength(1); expect(result.result).toBe("active_at_time_of_supply"); expect(result.statusAsOf).toBe(result.timeOfSupplyDate); expect(result.supplier).toEqual({ registrationId: REGISTRATION, evidenceHash: REGISTRATION_HASH }); expect(result.supplierServiceLocation).toEqual({ id: LOCATION, evidenceHash: LOCATION_HASH }); expect(result.supplierRegistrationStatusEvidenceHash).toBe(STATUS_HASH); expect(result.timeOfSupplyEvidenceHash).toBe(TOS_HASH); expect(result.timeOfSupply.evidenceHash).toBe(TOS_HASH); expect(result.timeOfSupply.branch).toBe("section13_2_a_invoice_or_payment"); expect(result.timeOfSupply.invoiceSeries).toBe("FY2043"); expect(result.timeOfSupply.amountMinor).toBe("10500"); deeplyFrozen(result); expect(result).not.toHaveProperty("tenantId");
    expect(statements[0]).toContain("current_setting('app.tenant_id', true)"); expect(statements[0]).toContain("tax_attribution_snapshot"); expect(statements[0]).toContain("india_gst_supplier_registration_status_snapshot"); expect(statements[0]).not.toMatch(/ORDER BY|LIMIT|now\s*\(|current_date|INSERT\s+INTO|UPDATE\s+public|DELETE\s+FROM|TRUNCATE|FOR\s+(UPDATE|SHARE)/i);
  });
  test("requires exact status/time equality before reading and fails closed for missing or duplicate rows", async () => {
    let calls = 0; const noRead = (async () => { calls += 1; return []; }) as unknown as Tx;
    await expect(new IndiaGstRegistrationAtTimeOfSupplyService().resolve(noRead, input({ timeOfSupplyDate: "2043-06-16" }) as never)).rejects.toBeInstanceOf(IndiaGstRegistrationAtTimeOfSupplyValidationError); expect(calls).toBe(0);
    await expect(new IndiaGstRegistrationAtTimeOfSupplyService().resolve(tx([]), input() as never)).rejects.toBeInstanceOf(IndiaGstRegistrationAtTimeOfSupplyNotFoundError);
    await expect(new IndiaGstRegistrationAtTimeOfSupplyService().resolve(tx([row(), row({ invoice_id: id(29590) })]), input() as never)).rejects.toBeInstanceOf(IndiaGstRegistrationAtTimeOfSupplyConflictError);
  });
  test("rejects malformed, inactive, contradictory and cross-lineage predecessor evidence", async () => {
    const service = new IndiaGstRegistrationAtTimeOfSupplyService();
    for (const defect of [{ gst_registration_status: "suspended" }, { location_supplier_evidence_hash: "9".repeat(64) }, { status_as_of: "2043-06-14" }, { lineage_reservation_id: id(29591) }, { attribution_snapshot: null }, { service_source: "other" }, { payment_date: "2043-06-14" }]) await expect(service.resolve(tx([row(defect)]), input() as never)).rejects.toBeInstanceOf(IndiaGstRegistrationAtTimeOfSupplyConflictError);
    await expect(service.resolve(tx([row()]), input({ supplierRegistrationStatusEvidenceHash: "9".repeat(64) }) as never)).rejects.toBeInstanceOf(IndiaGstRegistrationAtTimeOfSupplyConflictError);
    await expect(service.resolve(tx([row()]), input({ timeOfSupplyEvidenceHash: "8".repeat(64) }) as never)).rejects.toBeInstanceOf(IndiaGstRegistrationAtTimeOfSupplyConflictError);
  });
});
