import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { SQL } from "bun";
import { runMigrations } from "../scripts/migrate";
import { createApp } from "../src/app";
import { BearerTenantResolver, Hs256TokenSigner, LocalLoginGuard, LocalLoginService } from "../src/contexts/identity";
import type { PlaceRecord } from "../src/contexts/distribution";
import { MarketMapHttpApi } from "../src/http/market-map";
import { OperatorHttpApi } from "../src/http/operator";
import { Database } from "../src/kernel";

// Two explicit authorities on one isolated test server. Never borrow a PMS database.
const ADMIN = process.env.YELLOW_MARKET_MAP_ADMIN_URL;
const RUNTIME = process.env.YELLOW_MARKET_MAP_ADMIN_RUNTIME_URL;
if (process.env.YELLOW_REQUIRE_MARKET_MAP_DATABASE === "1" && (!ADMIN || !RUNTIME)) {
  throw new Error("Market map proof requires explicit deploy and runtime test-server URLs");
}
const suite = ADMIN && RUNTIME ? describe.serial : describe.skip;
const databaseName = `yellow_places_${crypto.randomUUID().replaceAll("-", "")}`;
const ids = Object.fromEntries(["tenantA", "tenantB", "brand", "own", "sibling", "foreign", "actor", "otherActor", "role", "otherRole"].map((key) => [key, crypto.randomUUID()])) as Record<string, string>;
const id = (key: string) => ids[key]!;
const scope = "rates.configuration:read";
const record: PlaceRecord = { id: "public-one", name: "Synthetic Public Hotel", longitude: 55, latitude: 25,
  category: "hotel", status: "unknown", address: null, country: "AE", websites: [], brand: null, confidence: null, sources: [] };
let admin: SQL | undefined; let fixture: SQL | undefined; let loginPool: SQL | undefined;
let database: Database | undefined; let created = false; let catalogReads = 0;
let app: ReturnType<typeof createApp>;
const signer = new Hs256TokenSigner("synthetic-market-map-secret-only-for-isolated-proof-2026");

function target(url: string): string { const parsed = new URL(url); parsed.pathname = `/${databaseName}`; return parsed.toString(); }

beforeAll(async () => {
  if (!ADMIN || !RUNTIME) return;
  const deployUrl = new URL(ADMIN); const runtimeUrl = new URL(RUNTIME);
  if (deployUrl.hostname !== runtimeUrl.hostname || deployUrl.port !== runtimeUrl.port
      || decodeURIComponent(deployUrl.username) !== "yellow_deploy"
      || decodeURIComponent(runtimeUrl.username) !== "yellow_runtime") throw new Error("Wrong isolated proof authority");
  admin = new SQL(ADMIN, { max: 1 });
  // databaseName is generated by this test from a fixed prefix plus UUID hex.
  await admin.unsafe(`CREATE DATABASE "${databaseName}" OWNER yellow_deploy`); created = true;
  await runMigrations({ databaseUrl: target(ADMIN) });
  fixture = new SQL(target(ADMIN), { max: 1 });
  database = Database.connect(target(RUNTIME), { maxConnections: 2, prepare: false });
  loginPool = new SQL(target(RUNTIME), { max: 1 });
  await fixture`INSERT INTO permission(code, description) VALUES (${scope}, 'Read market comparison context') ON CONFLICT (code) DO NOTHING`;
  await fixture`INSERT INTO tenant(id,slug,name,tier,status) VALUES
    (${id("tenantA")}::uuid,'places-proof-a','Places A','shared','active'),
    (${id("tenantB")}::uuid,'places-proof-b','Places B','shared','active')`;
  await fixture`INSERT INTO org_node(id,tenant_id,path,kind,name,timezone,currency) VALUES
    (${id("brand")}::uuid,${id("tenantA")}::uuid,'places_a','brand','Brand',NULL,NULL),
    (${id("own")}::uuid,${id("tenantA")}::uuid,'places_a.own','property','Own','Asia/Dubai','AED'),
    (${id("sibling")}::uuid,${id("tenantA")}::uuid,'places_a.sibling','property','Sibling','Asia/Dubai','AED'),
    (${id("foreign")}::uuid,${id("tenantB")}::uuid,'places_b.foreign','property','Foreign','Asia/Riyadh','SAR')`;
  await fixture`INSERT INTO app_user(id,tenant_id,email,display_name,auth,status) VALUES
    (${id("actor")}::uuid,${id("tenantA")}::uuid,'a@places.invalid','Operator A','{}'::jsonb,'active'),
    (${id("otherActor")}::uuid,${id("tenantB")}::uuid,'b@places.invalid','Operator B','{}'::jsonb,'active')`;
  await fixture`INSERT INTO role(id,tenant_id,name) VALUES
    (${id("role")}::uuid,${id("tenantA")}::uuid,'Rate Reader A'),
    (${id("otherRole")}::uuid,${id("tenantB")}::uuid,'Rate Reader B')`;
  await fixture`INSERT INTO role_permission(role_id,permission_code) VALUES (${id("role")}::uuid,${scope}),(${id("otherRole")}::uuid,${scope})`;
  await fixture`INSERT INTO user_role(tenant_id,user_id,role_id,scope_node) VALUES
    (${id("tenantA")}::uuid,${id("actor")}::uuid,${id("role")}::uuid,${id("own")}::uuid),
    (${id("tenantB")}::uuid,${id("otherActor")}::uuid,${id("otherRole")}::uuid,${id("foreign")}::uuid)`;
  app = createApp({ database, tenantResolver: new BearerTenantResolver(signer),
    operatorApi: new OperatorHttpApi(new LocalLoginService(loginPool, signer, new LocalLoginGuard())),
    marketMapApi: new MarketMapHttpApi({
      search() { catalogReads++; return { places: [record], truncated: false, ambiguous: false, release: "2026-08-19.0", schemaVersion: "1.18.0" }; },
      byIds(keys) { catalogReads++; return keys.map((key) => ({ ...record, id: key })); },
    }) });
}, 120_000);

afterAll(async () => {
  await database?.close(); await loginPool?.close(); await fixture?.close();
  if (created && admin) await admin.unsafe(`DROP DATABASE "${databaseName}"`);
  await admin?.close();
});

async function request(property: string, options: { tenant?: string; actor?: string; scope?: readonly string[]; selection?: boolean; anonymous?: boolean } = {}) {
  const token = options.anonymous ? undefined : await signer.issue({ tenantId: options.tenant ?? id("tenantA"), userId: options.actor ?? id("actor"), scopes: options.scope ?? [scope] });
  return app.handle(new Request(`http://yellow.test/api/v1/properties/${property}/market-map/${options.selection ? "selection" : "places?mode=keyword&q=Hotel"}`, {
    method: options.selection ? "POST" : "GET", headers: { ...(token ? { authorization: `Bearer ${token}` } : {}), "content-type": "application/json" },
    ...(options.selection ? { body: JSON.stringify({ subjectId: "public-one", competitorIds: ["public-two"] }) } : {}),
  }));
}

suite("RMS-PLACES-001 real signed HTTP and PostgreSQL property isolation", () => {
  test("an exact property grant permits reads and canonical research export", async () => {
    expect((await request(id("own"))).status).toBe(200);
    const exportResponse = await request(id("own"), { selection: true });
    expect(exportResponse.status).toBe(200);
    expect((await exportResponse.json()).operationalWrites).toBe(false);
  });
  test("foreign tenant and sibling properties are denied before any catalog call", async () => {
    const before = catalogReads;
    for (const property of [id("sibling"), id("foreign")]) for (const selection of [false, true]) {
      expect((await request(property, { selection })).status).toBe(403);
    }
    expect((await request(id("own"), { tenant: id("tenantB"), actor: id("otherActor") })).status).toBe(403);
    expect(catalogReads).toBe(before);
  });
  test("anonymous, missing-scope and inconsistent tenant/actor claims do not read the index", async () => {
    const before = catalogReads;
    expect((await request(id("own"), { anonymous: true })).status).toBe(401);
    expect((await request(id("own"), { scope: ["inventory.availability:read"] })).status).toBe(403);
    expect((await request(id("foreign"), { tenant: id("tenantB"), actor: id("actor") })).status).toBe(403);
    expect(catalogReads).toBe(before);
  });
  test("revoked grants and disabled actors are rechecked even with an unexpired token", async () => {
    await fixture!`UPDATE app_user SET status='disabled' WHERE id=${id("actor")}::uuid`;
    const before = catalogReads;
    expect((await request(id("own"))).status).toBe(403);
    await fixture!`UPDATE app_user SET status='active' WHERE id=${id("actor")}::uuid`;
    await fixture!`DELETE FROM role_permission WHERE role_id=${id("role")}::uuid AND permission_code=${scope}`;
    expect((await request(id("own"))).status).toBe(403);
    expect(catalogReads).toBe(before);
    await fixture!`INSERT INTO role_permission(role_id,permission_code) VALUES (${id("role")}::uuid,${scope})`;
  });
  test("ancestor grants admit descendants without crossing tenant boundaries", async () => {
    await fixture!`UPDATE user_role SET scope_node=${id("brand")}::uuid WHERE user_id=${id("actor")}::uuid`;
    expect((await request(id("own"))).status).toBe(200);
    expect((await request(id("sibling"))).status).toBe(200);
    expect((await request(id("foreign"))).status).toBe(403);
  });
});
