import { expect, test } from "bun:test";

const app = await Bun.file("frontend/yellow/src/App.tsx").text();
const css = await Bun.file("frontend/yellow/src/styles.css").text();

test("the mobile finance workbench reads cashier state and posts only through the governed charge endpoint", () => {
  expect(app).toContain('queryKey: ["cashier-snapshot", propertyId]');
  expect(app).toContain('`/api/v1/properties/${propertyId}/cashier-sessions`');
  expect(app).toContain('workspace=finance');
  expect(app).toContain('part === "cashiers"');
  expect(app).toContain("function CashierWorkbench");
  expect(app).toContain("Find any reservation or bill");
  expect(app).toContain("Search guest, reservation, room, source, channel or folio");
  expect(app).toContain("Exact folio reference");
  expect(app).toContain("const matchingStays");
  expect(app).toContain("const openFolioReference = async () =>");
  expect(app).toContain("Exact folio reference is accepted in the same search.");
  expect(app).toContain('stayScope === "all"');
  expect(app).toContain('`/api/v1/properties/${propertyId}/folios/${encodeURIComponent(reference)}/statement`');
  expect(app).toContain('`/api/v1/properties/${propertyId}/folios/${folioId}/charges`');
  expect(app).toContain('"idempotency-key": idempotencyKey');
  expect(app).toContain("selectedOption && validAmount && validQuantity");
  expect(app).toContain("if (!folio.data || !selectedOption || !canPost || !confirmed || posting || allocationLocked || depositInteractionLocked()) return;");
  expect(app).toContain("onLifecycleBusyChange?.(true)");
  expect(app).toContain("onLifecycleBusyChange?.(false)");
  expect(app).toContain("I confirm the selected class, amount and folio window. Post this immutable charge.");
  expect(app).toContain("disabled={!canPost || !confirmed || posting || depositLocked}");
  expect(app).toContain("server-owned catalogues and separate visible confirmations");
  expect(app).toContain("Balance <strong>{money(folio.data.balanceMinor, folio.data.folio.currency)}");
  expect(app).toContain("visiblePostingRows.map((row)");
  expect(app).not.toContain("folio.data.rows.slice(-6)");
  expect(app).toContain("stay.sellableUnitLabel");
  expect(app).toContain("stay.unitTypeLabel");
  expect(app).toContain('detail.data.reservation.folios.find((item) => item.status === "open")');
  expect(app).toContain('aria-label="Folio windows"');
  expect(app).toContain('aria-label="Posting classes"');
  expect(app).toContain('className="cashier-selected-stay"');
  expect(app).toContain("function CashierGroupIcon");
  expect(app).toContain('<CashierGroupIcon group={group} />');
  expect(app).toContain("data-status={stay.status}");
  expect(app).toContain("Cash drawer not configured");
  expect(app).toContain("Governed room, service and non-cash folio charges can still be posted above.");
  expect(app).toContain('role="status" aria-live="polite"');
  expect(app).toContain("No folio windows exist for this reservation.");
  expect(app).toContain("A governed folio window must be opened before charges can be reviewed or posted.");
  expect(app).not.toContain("{row.quantity} × {row.amountMinor}");
  expect(app).toContain("<FinanceWorkspace onLifecycleBusyChange={setReservationLifecycleFlight} />");
  expect(app).toContain("Split bill windows");
  expect(app).toContain("No partial amount split");
  expect(app).toContain("No server-returned complete charge groups are available in this window.");
  expect(app).toContain("Retry same transfer and reconcile");
});

test("Yellow composer styles do not override nested cashier forms", () => {
  expect(css).toContain(".yellow-command-surface > form { display: flex;");
  expect(css).toContain(".yellow-command-surface > form > input {");
  expect(css).toContain(".yellow-command-surface > form > button {");
  expect(css).not.toContain(".yellow-command-surface form { display: flex;");
  expect(css).not.toContain(".yellow-command-surface input {");
  expect(css).not.toContain(".yellow-command-surface form button {");
  expect(css).toContain(".cashier-charge-form { display: grid;");
  expect(css).toContain('.cashier-charge-form select, .cashier-charge-form input:not([type="checkbox"]) { width: 100%; min-height: 44px;');
  expect(css).toContain(".cashier-charge-form button { min-height: 44px;");
  expect(css).toContain(".cashier-charge-groups button { display: inline-flex; align-items: center; gap: 7px; min-width: 44px;");
  expect(css).toContain(".cashier-group-icon {");
  expect(css).toContain('.cashier-charge-groups button[data-group="food-and-beverage"]');
  expect(css).toContain('.cashier-charge-form .cashier-charge-groups button[data-group="food-and-beverage"] { color: #6a3a00; }');
  expect(css).toContain('.cashier-charge-form .cashier-charge-options button { min-height: 44px; border: 1px solid transparent; background: transparent; color: #34342f; }');
  expect(css).toContain('.cashier-charge-form .cashier-charge-options button.active { border-color: #d8b300; background: #fff; color: #292300; }');
  expect(css).toContain(".cashier-drawer-empty {");
  expect(css).toContain(".cashier-charge-form .cashier-confirm { grid-column: 1 / -1; display: flex; align-items: start; gap: 8px; min-height: 44px;");
  expect(css).toContain(".cashier-bill-allocation {");
  expect(css).toContain(".cashier-allocation-preview {");
  expect(css).toContain(".cashier-allocation-commit { width: 100%;");
});
