-- Order463: exact existing-table caller authority, no schema or RLS change.
-- id is generated by PostgreSQL; only active is mutable. The service binds
-- subject_type='reservation' and locks the tenant/property reservation before
-- every command. This is named direct-SQL capability debt, not a raw DB API.
-- No PUBLIC/yellow_runtime grant, broad UPDATE, DELETE or TRUNCATE is added.
GRANT INSERT (tenant_id, subject_type, subject_id, code, message, show_on, active)
  ON public.alert TO app_role;
GRANT UPDATE (active) ON public.alert TO app_role;
