export interface IndependentReviewCoverage {
  readonly throughOrder: number;
  readonly approvedReviewFiles: readonly string[];
}

const REVIEW_DIRECTORY = new URL("../handoff/reviews/", import.meta.url);
const GENERATED_MODULE = new URL("../src/generated/review-coverage.ts", import.meta.url);

export function approvedReviewEnd(source: string): number | undefined {
  const reviewer = source.match(/^\*\*Reviewed by:\*\*\s*(.+)$/im)?.[1] ?? "";
  if (!/architect role/i.test(reviewer)) return undefined;

  const verdict = (source.match(/\*\*Verdict:\*\*\s*(.+)$/im)?.[1] ?? "")
    .replace(/\*/g, "")
    .trim();
  if (!/^APPROVED\b/i.test(verdict)) return undefined;

  const range = source.match(/^# REVIEW\s+(\d{3})(?:[–-](\d{3}))?\b/m);
  if (!range) return undefined;
  const end = Number(range[2] ?? range[1]);
  return Number.isSafeInteger(end) && end > 0 ? end : undefined;
}

export async function deriveIndependentReviewCoverage(
  directory = REVIEW_DIRECTORY,
): Promise<IndependentReviewCoverage> {
  const approvedReviewFiles: string[] = [];
  let throughOrder = 0;
  const fileNames: string[] = [];
  for await (const fileName of new Bun.Glob("*.md").scan({ cwd: directory.pathname, onlyFiles: true })) {
    fileNames.push(fileName);
  }
  fileNames.sort((left, right) => left.localeCompare(right));
  for (const fileName of fileNames) {
    const source = await Bun.file(new URL(fileName, directory)).text();
    const end = approvedReviewEnd(source);
    if (end === undefined) continue;
    approvedReviewFiles.push(fileName);
    throughOrder = Math.max(throughOrder, end);
  }
  return Object.freeze({ throughOrder, approvedReviewFiles: Object.freeze(approvedReviewFiles) });
}

export function renderReviewCoverageModule(coverage: IndependentReviewCoverage): string {
  const files = coverage.approvedReviewFiles.map((fileName) => `  ${JSON.stringify(fileName)},`).join("\n");
  return `// Generated by scripts/derive-review-coverage.ts from approved architect review documents.\n` +
    `// Do not edit this file directly. Run: bun scripts/derive-review-coverage.ts --write\n` +
    `export const APPROVED_REVIEW_FILES = Object.freeze([\n${files}\n] as const);\n` +
    `export const INDEPENDENTLY_REVIEWED_THROUGH_ORDER = ${coverage.throughOrder};\n`;
}

if (import.meta.main) {
  const mode = process.argv[2] ?? "--check";
  if (mode !== "--check" && mode !== "--write") {
    throw new Error("usage: bun scripts/derive-review-coverage.ts [--check|--write]");
  }
  const expected = renderReviewCoverageModule(await deriveIndependentReviewCoverage());
  if (mode === "--write") {
    await Bun.write(GENERATED_MODULE, expected);
    process.stdout.write("Generated independent review coverage.\n");
  } else {
    const actual = await Bun.file(GENERATED_MODULE).text();
    if (actual !== expected) throw new Error("generated review coverage is stale; run with --write");
    process.stdout.write("Generated independent review coverage is exact.\n");
  }
}
