import { types as utilTypes } from "node:util";
import type { Tx } from "../../kernel";
import { parsePositiveTaxAttributionSnapshot } from "./attribution";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/, HASH=/^[0-9a-f]{64}$/, DATE=/^(\d{4})-(\d{2})-(\d{2})$/;
const KEYS=["tenantId","propertyNode","reservationId","serviceProvisionSnapshotId","invoiceIssueSnapshotId","serviceProvisionDate","invoiceIssueDate","ordinaryRegimeSource","ordinaryRegimeEvidenceSha256"] as const;
export interface IndiaGstAccommodationInvoiceTimelinessInput { readonly tenantId:string;readonly propertyNode:string;readonly reservationId:string;readonly serviceProvisionSnapshotId:string;readonly invoiceIssueSnapshotId:string;readonly serviceProvisionDate:string;readonly invoiceIssueDate:string;readonly ordinaryRegimeSource:string;readonly ordinaryRegimeEvidenceSha256:string }
export type IndiaGstAccommodationInvoiceTimeliness = "timely" | "late";
export interface IndiaGstAccommodationInvoiceTimelinessResult { readonly invoiceIssueSnapshotId:string;readonly serviceProvisionSnapshotId:string;readonly propertyNode:string;readonly serviceProvisionDate:string;readonly invoiceIssueDate:string;readonly deadlineDate:string;readonly regime:"ordinary_rule47_30_day";readonly source:"governed_rule47_ordinary_regime_record";readonly legalRule:"CGST_RULE_47_ORDINARY_SERVICE_INVOICE_30_DAY_INPUT";readonly result:"timely"|"late";readonly amountMinor:string;readonly currency:string;readonly evidenceHash:string }
export class IndiaGstAccommodationInvoiceTimelinessValidationError extends Error { constructor(m:string){super(m);this.name="IndiaGstAccommodationInvoiceTimelinessValidationError"} }
export class IndiaGstAccommodationInvoiceTimelinessNotFoundError extends Error { constructor(m:string){super(m);this.name="IndiaGstAccommodationInvoiceTimelinessNotFoundError"} }
export class IndiaGstAccommodationInvoiceTimelinessConflictError extends Error { constructor(m:string){super(m);this.name="IndiaGstAccommodationInvoiceTimelinessConflictError"} }
type Row=Record<string,unknown>;
function exact(v:unknown,k:readonly string[],s:string,E:ErrorConstructor=IndiaGstAccommodationInvoiceTimelinessValidationError):Row {if(typeof v!=="object"||v===null||Array.isArray(v)||utilTypes.isProxy(v)||Object.getOwnPropertySymbols(v).length||(Object.getPrototypeOf(v)!==Object.prototype&&Object.getPrototypeOf(v)!==null))throw new E(`${s} must be an exact plain object`);const d=Object.getOwnPropertyDescriptors(v),a=Object.keys(d).sort(),x=[...k].sort();if(a.length!==x.length||a.some((q,i)=>q!==x[i])||Object.values(d).some(q=>q.get!==undefined||q.set!==undefined||q.enumerable!==true||!("value"in q)))throw new E(`${s} shape is invalid`);return v as Row}
const uuid=(v:unknown,s:string)=>{if(typeof v!=="string"||!UUID.test(v))throw new IndiaGstAccommodationInvoiceTimelinessConflictError(`${s} is invalid`);return v};
const sha=(v:unknown,s:string)=>{if(typeof v!=="string"||!HASH.test(v))throw new IndiaGstAccommodationInvoiceTimelinessConflictError(`${s} is invalid`);return v};
function dt(v:unknown,s:string){if(typeof v!=="string"||!DATE.test(v))throw new IndiaGstAccommodationInvoiceTimelinessConflictError(`${s} is invalid`);const m=DATE.exec(v)!,y=+m[1],mo=+m[2],d=+m[3],leap=y%4===0&&(y%100!==0||y%400===0),days=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31];if(y===0||mo<1||mo>12||d<1||d>(days[mo-1]??0))throw new IndiaGstAccommodationInvoiceTimelinessConflictError(`${s} is invalid`);return v}
function sum(v:unknown){return new Bun.CryptoHasher("sha256").update(JSON.stringify(v)).digest("hex")}
function deadline(s:string){const [y,m,d]=s.split("-").map(Number) as [number,number,number],x=new Date(Date.UTC(y,m-1,d+30));return `${String(x.getUTCFullYear()).padStart(4,"0")}-${String(x.getUTCMonth()+1).padStart(2,"0")}-${String(x.getUTCDate()).padStart(2,"0")}`}
const ROW=["tenant_id","invoice_issue_snapshot_id","service_provision_snapshot_id","property_node","reservation_id","service_provision_date","invoice_issue_date","currency","amount_minor","coverage_scope","invoice_issue_source","invoice_issue_evidence_sha256","invoice_legal_rule","service_provision_source","service_provision_evidence_sha256","service_legal_rule","reservation_lineage_id","hold_binding_id","attribution_id","segment_id","origin_quote_hash","snapshot_hash","service_currency","lineage_id","lineage_property_node","lineage_hold_binding_id","lineage_attribution_id","lineage_reservation_id","lineage_segment_id","lineage_origin_quote_hash","lineage_snapshot_hash","lineage_currency","attribution_snapshot","ordinary_regime_source","ordinary_regime_legal_rule"] as const;
function build(r:Row,i:IndiaGstAccommodationInvoiceTimelinessInput):IndiaGstAccommodationInvoiceTimelinessResult {const t=uuid(r.tenant_id,"tenant"),p=uuid(r.property_node,"property"),res=uuid(r.reservation_id,"reservation"),s=uuid(r.service_provision_snapshot_id,"service snapshot"),inv=uuid(r.invoice_issue_snapshot_id,"invoice snapshot"),sd=dt(r.service_provision_date,"service date"),id=dt(r.invoice_issue_date,"invoice date");if(t!==i.tenantId||p!==i.propertyNode||res!==i.reservationId||s!==i.serviceProvisionSnapshotId||inv!==i.invoiceIssueSnapshotId||sd!==i.serviceProvisionDate||id!==i.invoiceIssueDate||r.coverage_scope!=="full_attribution"||r.currency!==r.service_currency||r.invoice_issue_source!=="governed_supplier_tax_invoice_record"||r.invoice_legal_rule!=="CGST_ACT_13_2_INVOICE_DATE_INPUT_ONLY"||r.service_provision_source!=="governed_service_provision_record"||r.service_legal_rule!=="CGST_ACT_13_2_B_SERVICE_PROVISION_DATE_INPUT_ONLY")throw new IndiaGstAccommodationInvoiceTimelinessConflictError("evidence conflicts with complete lineage");if(r.ordinary_regime_source!==undefined&&r.ordinary_regime_source!=="governed_rule47_ordinary_regime_record")throw new IndiaGstAccommodationInvoiceTimelinessConflictError("unsupported regime");if(r.ordinary_regime_legal_rule!==undefined&&r.ordinary_regime_legal_rule!=="CGST_RULE_47_ORDINARY_SERVICE_INVOICE_30_DAY_INPUT")throw new IndiaGstAccommodationInvoiceTimelinessConflictError("unsupported regime");sha(i.ordinaryRegimeEvidenceSha256,"regime evidence");sha(r.origin_quote_hash,"quote");sha(r.snapshot_hash,"snapshot");try{const a=parsePositiveTaxAttributionSnapshot(r.attribution_snapshot);if(a.origin.kind!=="rate_quote"||a.origin.quoteHash!==r.origin_quote_hash||a.snapshotHash!==r.snapshot_hash||a.currency!==r.currency||a.revenueLine.lineId!=="room"||a.revenueLine.revenueGroup!=="room_revenue"||a.evaluation.grandTotalMinor.toString()!==String(r.amount_minor))throw 0}catch{throw new IndiaGstAccommodationInvoiceTimelinessConflictError("canonical attribution is malformed")}const pub={invoiceIssueSnapshotId:inv,serviceProvisionSnapshotId:s,propertyNode:p,serviceProvisionDate:sd,invoiceIssueDate:id,deadlineDate:deadline(sd),regime:"ordinary_rule47_30_day" as const,source:"governed_rule47_ordinary_regime_record" as const,legalRule:"CGST_RULE_47_ORDINARY_SERVICE_INVOICE_30_DAY_INPUT" as const,result:id<=deadline(sd)?"timely" as const:"late" as const,amountMinor:String(r.amount_minor),currency:String(r.currency)};return Object.freeze({...pub,evidenceHash:sum({tenantId:t,...pub})})}
export class IndiaGstAccommodationInvoiceTimelinessService {async resolve(tx:Tx,input:IndiaGstAccommodationInvoiceTimelinessInput){if(typeof tx!=="function")throw new IndiaGstAccommodationInvoiceTimelinessValidationError("tenant transaction is unavailable");const i=exact(input,KEYS,"invoice-timeliness input") as unknown as IndiaGstAccommodationInvoiceTimelinessInput;if(i.ordinaryRegimeSource!=="governed_rule47_30_day")throw new IndiaGstAccommodationInvoiceTimelinessValidationError("unsupported regime");const rows=await tx<Row[]>`SELECT invoice_issue_snapshot_id, service_provision_snapshot_id, tenant_id, property_node, reservation_id, service_provision_date, invoice_issue_date, currency, amount_minor, coverage_scope, invoice_issue_source, invoice_issue_evidence_sha256, invoice_legal_rule, service_provision_source, service_provision_evidence_sha256, service_legal_rule, reservation_lineage_id, hold_binding_id, attribution_id, origin_quote_hash, snapshot_hash, service_currency, lineage_id, lineage_property_node, lineage_hold_binding_id, lineage_attribution_id, lineage_reservation_id, lineage_segment_id, lineage_origin_quote_hash, lineage_snapshot_hash, lineage_currency, attribution_snapshot, ordinary_regime_source, ordinary_regime_legal_rule FROM public.india_gst_accommodation_invoice_issue_snapshot JOIN public.india_gst_accommodation_service_provision_snapshot USING (tenant_id, service_provision_snapshot_id) WHERE tenant_id=${i.tenantId}::uuid AND tenant_id=current_setting('app.tenant_id', true)::uuid AND invoice_issue_snapshot_id=${i.invoiceIssueSnapshotId}::uuid AND service_provision_snapshot_id=${i.serviceProvisionSnapshotId}::uuid AND invoice_issue_date=${i.invoiceIssueDate}::date AND service_provision_date=${i.serviceProvisionDate}::date AND property_node=${i.propertyNode}::uuid AND reservation_id=${i.reservationId}::uuid AND coverage_scope='full_attribution'`;if(!rows.length)throw new IndiaGstAccommodationInvoiceTimelinessNotFoundError("selected invoice timeliness evidence is unavailable");if(rows.length!==1||rows[0]===undefined)throw new IndiaGstAccommodationInvoiceTimelinessConflictError("selected invoice timeliness evidence is ambiguous");return build(rows[0],i)}}
