/**
 * The product map is deliberately data-first. A record is a promise about
 * presentation, not proof that a backend capability exists. Keep the status
 * and prerequisite honest when a surface is only a roadmap item.
 */

export const CAPABILITY_STATUSES = ["live", "beta", "preview", "blocked", "planned"] as const;
export type CapabilityStatus = (typeof CAPABILITY_STATUSES)[number];

export const ECOSYSTEM_MODULES = [
  "today",
  "reservations",
  "front-desk",
  "rooms",
  "housekeeping",
  "guest-services",
  "cashiering",
  "finance",
  "revenue",
  "distribution",
  "crm",
  "groups-events",
  "maintenance-assets",
  "food-ancillaries",
  "purchasing-inventory",
  "analytics",
  "compliance",
  "property-setup",
  "integrations",
  "guest-mobile",
] as const;
export type EcosystemModule = (typeof ECOSYSTEM_MODULES)[number];

export const CAPABILITY_AUDIENCES = [
  "hotel-operator",
  "hotel-manager",
  "finance-team",
  "revenue-team",
  "distribution-team",
  "property-admin",
  "guest",
  "yellow-devices",
] as const;
export type CapabilityAudience = (typeof CAPABILITY_AUDIENCES)[number];

export const DEVICE_CLASSES = ["desktop", "tablet", "mobile"] as const;
export type DeviceClass = (typeof DEVICE_CLASSES)[number];

export type CapabilityRecord = Readonly<{
  /** Stable identifier. Do not derive this from visible copy. */
  key: string;
  module: EcosystemModule;
  label: string;
  summary: string;
  status: CapabilityStatus;
  audience: readonly CapabilityAudience[];
  devices: readonly DeviceClass[];
  prerequisite: string;
  /** A live route is navigable; a preview route is presentation-only. */
  route: string;
  operationalPurpose: string;
  statusReason: string;
  existing: boolean;
}>;

type CapabilitySeed = Omit<CapabilityRecord, "existing"> & Partial<Pick<CapabilityRecord, "existing">>;

const record = (seed: CapabilitySeed): CapabilityRecord => Object.freeze({
  ...seed,
  existing: seed.existing ?? (seed.status === "live" || seed.status === "beta"),
  audience: Object.freeze([...seed.audience]),
  devices: Object.freeze([...seed.devices]),
});

const operatorDevices = ["desktop", "tablet"] as const satisfies readonly DeviceClass[];
const allDevices = ["desktop", "tablet", "mobile"] as const satisfies readonly DeviceClass[];

/**
 * Complete approved ecosystem index. Existing Order582 surfaces are the only
 * live/beta records; every other item has a visible boundary instead of a
 * fabricated success state.
 */
export const CAPABILITY_REGISTRY: readonly CapabilityRecord[] = Object.freeze([
  record({ key: "today.command-centre", module: "today", label: "Today", summary: "The property's current arrival, departure and in-house command centre.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Authenticated property access", route: "/p/:propertyId/today", operationalPurpose: "Orient the team around current hotel work without inferring state.", statusReason: "Serving read-only Today workspace is available.", existing: true }),
  record({ key: "today.overwatch", module: "today", label: "Overwatch", summary: "A cross-signal operating view for exceptions and handoffs.", status: "preview", audience: ["hotel-manager", "hotel-operator"], devices: operatorDevices, prerequisite: "Approved exception and alert contracts", route: "/ecosystem/preview/today-overwatch", operationalPurpose: "Unify governed operational signals when their source contracts are accepted.", statusReason: "Preview only: no cross-domain alert authority or inferred exception feed exists yet.", existing: false }),

  record({ key: "reservations.board", module: "reservations", label: "Reservations", summary: "Reservation search, movement lanes and stay detail.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Authenticated property access", route: "/p/:propertyId/reservations", operationalPurpose: "Find and review the authoritative reservation state.", statusReason: "Serving reservation workspace is available.", existing: true }),
  record({ key: "reservations.detail", module: "reservations", label: "Reservation detail", summary: "A governed stay record with current readiness and guest allocation.", status: "live", audience: ["hotel-operator"], devices: operatorDevices, prerequisite: "A reservation identifier from the board", route: "/p/:propertyId/res/:reservationId", operationalPurpose: "Keep operational changes anchored to one authoritative stay.", statusReason: "Existing reservation detail route is available.", existing: true }),
  record({ key: "reservations.crs", module: "reservations", label: "CRS workspace", summary: "Central reservation control across direct and partner demand.", status: "preview", audience: ["hotel-manager", "distribution-team"], devices: operatorDevices, prerequisite: "Channel and booking-source contracts", route: "/ecosystem/preview/reservations-crs", operationalPurpose: "Coordinate reservation sources without creating duplicate authority.", statusReason: "Preview only: source certification, mapping and acknowledgement contracts are pending.", existing: false }),
  record({ key: "reservations.availability", module: "reservations", label: "Availability board", summary: "A visual sellability and room-type planning surface.", status: "planned", audience: ["hotel-manager", "revenue-team"], devices: operatorDevices, prerequisite: "PostgreSQL-authoritative availability projection", route: "/ecosystem/preview/availability-board", operationalPurpose: "Review sellability decisions before a governed booking command.", statusReason: "Planned: no separate board surface is authorized in this shell.", existing: false }),
  record({ key: "reservations.booking-engine", module: "reservations", label: "Booking engine", summary: "Direct demand capture for the property's own channels.", status: "blocked", audience: ["hotel-manager", "distribution-team"], devices: allDevices, prerequisite: "Published booking-engine contract, payment edge and property policy", route: "/ecosystem/preview/booking-engine", operationalPurpose: "Offer direct booking without bypassing inventory or payment authority.", statusReason: "Blocked until payment-edge and publication contracts are independently accepted.", existing: false }),

  record({ key: "front-desk.arrivals-departures", module: "front-desk", label: "Arrivals & departures", summary: "Today lanes for arrival, departure and in-house preparation.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Today and reservation reads", route: "/p/:propertyId/today", operationalPurpose: "Give front desk staff the next governed operational step.", statusReason: "Existing Today journey is available.", existing: true }),
  record({ key: "front-desk.check-in-readiness", module: "front-desk", label: "Check-in readiness", summary: "Server-owned readiness before a check-in command.", status: "live", audience: ["hotel-operator"], devices: operatorDevices, prerequisite: "Due-in reservation and current room truth", route: "/p/:propertyId/res/:reservationId", operationalPurpose: "Expose blockers before staff confirms a check-in.", statusReason: "Existing reservation readiness flow is available.", existing: true }),
  record({ key: "front-desk.ai-arrival-departure-run", module: "front-desk", label: "AI check-in & checkout run", summary: "A visible, reconfirmed progress run for arrival and departure work.", status: "preview", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Accepted minibar, room inspection, luggage, folio and escalation command contracts", route: "/ecosystem/preview/ai-arrival-departure-run", operationalPurpose: "Show each governed check and escalation while keeping the operator in control.", statusReason: "Preview only: Yellow does not claim it can complete the cross-department procedure yet.", existing: false }),
  record({ key: "front-desk.command-centre", module: "front-desk", label: "Front desk command centre", summary: "A single front-office handoff surface for the active shift.", status: "preview", audience: ["hotel-manager", "hotel-operator"], devices: operatorDevices, prerequisite: "Accepted cross-workspace task and alert contract", route: "/ecosystem/preview/front-desk-command-centre", operationalPurpose: "Reduce shift handoff cost while preserving each context's authority.", statusReason: "Preview only: no new command centre authority is being simulated.", existing: false }),

  record({ key: "rooms.board", module: "rooms", label: "Rooms", summary: "Current room condition, occupancy and task context.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Operational room and housekeeping reads", route: "/p/:propertyId/operations", operationalPurpose: "See room readiness and operational blocks from current source truth.", statusReason: "Existing Operations room view is available.", existing: true }),
  record({ key: "rooms.assignment", module: "rooms", label: "Room assignment", summary: "A governed room selection flow for eligible stays.", status: "beta", audience: ["hotel-operator"], devices: operatorDevices, prerequisite: "Reservation readiness and server-owned candidate rooms", route: "/p/:propertyId/res/:reservationId", operationalPurpose: "Assign a room only when the authoritative candidate set permits it.", statusReason: "Available through the existing stay journey with bounded coverage.", existing: true }),
  record({ key: "rooms.inventory", module: "rooms", label: "Room inventory", summary: "Configured room types, spaces and sellable units.", status: "beta", audience: ["hotel-manager", "property-admin"], devices: operatorDevices, prerequisite: "Property inventory configuration", route: "/p/:propertyId/today?workspace=rates", operationalPurpose: "Review configured sellable room inventory without claiming a new editor.", statusReason: "Current catalogue is visible inside the commercial workspace; a standalone editor is not live.", existing: true }),
  record({ key: "rooms.plan-timeline", module: "rooms", label: "Room plan timeline", summary: "A day-by-day room and non-room allocation board inspired by proven PMS planning views.", status: "preview", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Authoritative occupancy, room-condition and assignment projections", route: "/ecosystem/preview/room-plan-timeline", operationalPurpose: "Spot gaps, conflicts and upgrade opportunities without mutating occupancy from a projection.", statusReason: "Preview only: the visual plan has no drag, assignment or occupancy authority.", existing: false }),

  record({ key: "housekeeping.tasks", module: "housekeeping", label: "Housekeeping tasks", summary: "Assigned room work with explicit staff declarations.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Authenticated property access", route: "/p/:propertyId/housekeeping", operationalPurpose: "Progress physical room work without inferring completion.", statusReason: "Serving Housekeeping workspace is available.", existing: true }),
  record({ key: "housekeeping.inspection", module: "housekeeping", label: "Inspection", summary: "Supervisor inspection distinct from physical cleaning.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "An eligible Housekeeping task", route: "/p/:propertyId/housekeeping", operationalPurpose: "Record the next explicit room-condition declaration.", statusReason: "Inspection actions are available in the existing Housekeeping flow.", existing: true }),
  record({ key: "housekeeping.quality-audits", module: "housekeeping", label: "Inspection & quality audits", summary: "Supervisor scorecards, evidence and recurring room-quality findings.", status: "preview", audience: ["hotel-manager", "hotel-operator"], devices: allDevices, prerequisite: "Inspection templates, evidence retention and accountable reviewer roles", route: "/ecosystem/preview/inspection-quality-audits", operationalPurpose: "Turn room inspections into traceable coaching and recurring-defect prevention.", statusReason: "Preview only: no audit score or evidence record is created.", existing: false }),
  record({ key: "housekeeping.linen-lost-found", module: "housekeeping", label: "Linen & lost property", summary: "Operational custody records for linen and guest property.", status: "planned", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Accepted custody and inventory contracts", route: "/ecosystem/preview/linen-lost-found", operationalPurpose: "Keep physical custody accountable when the required records exist.", statusReason: "Planned: no custody write or inventory authority is exposed here.", existing: false }),

  record({ key: "guest-services.requests", module: "guest-services", label: "Guest requests", summary: "Service requests with an accountable owner and status.", status: "preview", audience: ["hotel-operator", "hotel-manager"], devices: allDevices, prerequisite: "Guest-service task and notification contracts", route: "/ecosystem/preview/guest-requests", operationalPurpose: "Route and close guest requests without inventing fulfilment.", statusReason: "Preview only: service task orchestration is not live.", existing: false }),
  record({ key: "guest-services.messaging", module: "guest-services", label: "Guest messaging", summary: "A consent-aware conversation surface for stay support.", status: "blocked", audience: ["hotel-operator", "guest"], devices: allDevices, prerequisite: "Consent, identity and message-retention policy", route: "/ecosystem/preview/guest-messaging", operationalPurpose: "Support a guest conversation with auditable identity and delivery.", statusReason: "Blocked pending privacy, consent and delivery contracts.", existing: false }),
  record({ key: "guest-services.transport", module: "guest-services", label: "Transport & concierge", summary: "Pickup, transfer and concierge coordination.", status: "planned", audience: ["hotel-operator", "guest"], devices: allDevices, prerequisite: "Supplier and guest-request contracts", route: "/ecosystem/preview/transport-concierge", operationalPurpose: "Coordinate requested services without claiming supplier confirmation.", statusReason: "Planned: no supplier booking or fulfilment is connected.", existing: false }),
  record({ key: "guest-services.recovery-cases", module: "guest-services", label: "Guest recovery cases", summary: "One accountable view for complaints, recovery promises, costs and follow-up.", status: "preview", audience: ["hotel-manager", "hotel-operator"], devices: allDevices, prerequisite: "Case ownership, compensation approval and guest-consent policies", route: "/ecosystem/preview/guest-recovery-cases", operationalPurpose: "Prevent service failures and recovery commitments from disappearing between shifts.", statusReason: "Preview only: no compensation or outbound message is authorized.", existing: false }),
  record({ key: "guest-services.universal-search", module: "guest-services", label: "Universal hotel search", summary: "Multi-parameter retrieval across guests, stays, rooms, folios, companies, groups and tasks.", status: "preview", audience: ["hotel-operator", "hotel-manager", "finance-team"], devices: operatorDevices, prerequisite: "Tenant-scoped search projections and per-result access policy", route: "/ecosystem/preview/universal-search", operationalPurpose: "Find the right operational record without forcing staff to know which module owns it.", statusReason: "Preview only: search indexing and cross-domain authorization are not connected.", existing: false }),

  record({ key: "cashiering.desk", module: "cashiering", label: "Cashier & folios", summary: "Folio selection, charges and governed cashier actions.", status: "live", audience: ["hotel-operator", "finance-team"], devices: operatorDevices, prerequisite: "Authenticated property access and eligible folio", route: "/p/:propertyId/today?workspace=finance", operationalPurpose: "Review and post permitted folio activity through finance authority.", statusReason: "Existing cashier and folio workspace is available.", existing: true }),
  record({ key: "cashiering.deposits", module: "cashiering", label: "Hosted deposits", summary: "Deposit request status and hosted instrument handoff.", status: "live", audience: ["hotel-operator", "finance-team"], devices: operatorDevices, prerequisite: "Hosted PSP request and folio eligibility", route: "/p/:propertyId/today?workspace=finance", operationalPurpose: "Keep payment data at the hosted edge while showing exact status.", statusReason: "Existing hosted-deposit flow is available; no PAN is handled by Yellow.", existing: true }),
  record({ key: "cashiering.folio-windows", module: "cashiering", label: "Flexible folio windows 1–9", summary: "A responsive single-to-nine-window bill workspace for routing and settlement context.", status: "preview", audience: ["hotel-operator", "finance-team"], devices: operatorDevices, prerequisite: "Accepted folio-window projection, routing and balanced-transfer commands", route: "/ecosystem/preview/folio-windows", operationalPurpose: "Keep itemized charges visible while staff compare, route and settle the correct bill window.", statusReason: "Preview only: the selector does not create windows or move charges.", existing: false }),
  record({ key: "cashiering.itemized-kot", module: "cashiering", label: "Itemized bills & KOT", summary: "Outlet tickets with dishes, sides, taxes, service charges and posting references.", status: "planned", audience: ["hotel-operator", "finance-team"], devices: operatorDevices, prerequisite: "Menu, outlet, KOT, tax and folio-posting contracts", route: "/ecosystem/preview/itemized-kot", operationalPurpose: "Explain the complete guest bill beyond broad posting categories.", statusReason: "Planned: no menu catalogue or KOT authority is connected.", existing: false }),
  record({ key: "cashiering.payment-disputes", module: "cashiering", label: "Payment disputes & evidence", summary: "A case file for contested payments, receipts, correspondence and deadlines.", status: "preview", audience: ["finance-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Payment-provider evidence, retention and dispute authority", route: "/ecosystem/preview/payment-disputes", operationalPurpose: "Give finance one auditable place to prepare a dispute response.", statusReason: "Preview only: no evidence is submitted and no provider case is changed.", existing: false }),
  record({ key: "cashiering.reconciliation", module: "cashiering", label: "Cash reconciliation", summary: "Drawer and settlement reconciliation for cashier teams.", status: "preview", audience: ["finance-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Cash-drawer and settlement contracts", route: "/ecosystem/preview/cash-reconciliation", operationalPurpose: "Reconcile custody evidence without changing ledger authority.", statusReason: "Preview only: a complete reconciliation surface is not live.", existing: false }),

  record({ key: "finance.control-centre", module: "finance", label: "Financial control centre", summary: "Finance readiness, folios and current accounting handoffs.", status: "live", audience: ["finance-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Authenticated property access", route: "/p/:propertyId/today?workspace=finance", operationalPurpose: "Keep money movements tied to governed folio and journal commands.", statusReason: "Existing finance workspace is available.", existing: true }),
  record({ key: "finance.ap-ar", module: "finance", label: "Receivables & payables", summary: "Company billing and supplier balances.", status: "preview", audience: ["finance-team"], devices: operatorDevices, prerequisite: "Receivable/payable party contracts and posting authority", route: "/ecosystem/preview/finance-ap-ar", operationalPurpose: "Manage counterparties without bypassing journal and document controls.", statusReason: "Preview only: no standalone AP/AR workspace is exposed.", existing: false }),
  record({ key: "finance.fiscal-documents", module: "finance", label: "Fiscal documents", summary: "Invoice and statutory-document readiness.", status: "blocked", audience: ["finance-team", "property-admin"], devices: operatorDevices, prerequisite: "Property fiscal identity, series and statutory evidence", route: "/ecosystem/preview/fiscal-documents", operationalPurpose: "Issue compliant documents only after server-side eligibility is proven.", statusReason: "Blocked until the property's statutory evidence and fiscal series are ready.", existing: false }),

  record({ key: "revenue.rate-strategy", module: "revenue", label: "Rate strategy", summary: "Commercial rates and distribution configuration.", status: "live", audience: ["revenue-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Property commercial configuration", route: "/p/:propertyId/today?workspace=rates", operationalPurpose: "Review current rate and inventory configuration.", statusReason: "Existing commercial workspace is available.", existing: true }),
  record({ key: "revenue.rms-recommendations", module: "revenue", label: "RMS recommendations", summary: "Demand-aware pricing recommendations with explanation.", status: "planned", audience: ["revenue-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Approved source data, cost policy and human approval workflow", route: "/ecosystem/preview/rms-recommendations", operationalPurpose: "Help revenue teams evaluate a recommendation before any rate command.", statusReason: "Planned: no autonomous pricing or external model feed is enabled.", existing: false }),
  record({ key: "revenue.demand-signals", module: "revenue", label: "Demand signals", summary: "A bounded market-signal analysis view.", status: "preview", audience: ["revenue-team"], devices: operatorDevices, prerequisite: "Internal synthetic lab flag and approved signal contracts", route: "/ecosystem/preview/demand-signals", operationalPurpose: "Inspect signal semantics without presenting provider data as observed truth.", statusReason: "Preview only: external demand signals are not operational data.", existing: false }),
  record({ key: "revenue.ai-decisions", module: "revenue", label: "AI revenue decisions", summary: "Explainable pricing recommendations, evidence, confidence and approval boundaries.", status: "preview", audience: ["revenue-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Approved demand sources, recommendation policy and human approval", route: "/ecosystem/preview/ai-revenue-decisions", operationalPurpose: "Help revenue teams decide quickly without granting autonomous rate authority.", statusReason: "Preview only: no live market feed or rate command is attached.", existing: false }),

  record({ key: "distribution.channel-manager", module: "distribution", label: "Channel manager", summary: "Partner mapping, delivery and acknowledgement controls.", status: "preview", audience: ["distribution-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Partner certification and property-authorized mappings", route: "/ecosystem/preview/channel-manager", operationalPurpose: "Coordinate channel changes with explicit partner receipts.", statusReason: "Preview only: no partner delivery is claimed by this shell.", existing: false }),
  record({ key: "distribution.ari", module: "distribution", label: "ARI controls", summary: "Availability, rates and inventory distribution.", status: "blocked", audience: ["distribution-team", "revenue-team"], devices: operatorDevices, prerequisite: "Certified partner contract and PostgreSQL sellability authority", route: "/ecosystem/preview/ari-controls", operationalPurpose: "Publish only the exact commercial truth accepted by the property.", statusReason: "Blocked until a partner contract and end-to-end receipt proof exist.", existing: false }),
  record({ key: "distribution.connectivity", module: "distribution", label: "Connectivity", summary: "Partner health and source-contract diagnostics.", status: "planned", audience: ["distribution-team", "property-admin"], devices: operatorDevices, prerequisite: "Approved connector registry and secret boundary", route: "/ecosystem/preview/connectivity", operationalPurpose: "Explain connector health without exposing credentials or pretending connectivity.", statusReason: "Planned: connectors are not enabled by the ecosystem preview.", existing: false }),
  record({ key: "distribution.ai-channel-mapping", module: "distribution", label: "AI channel delivery & mapping", summary: "Mapping differences, delivery receipts and suggested repairs across approved channels.", status: "preview", audience: ["distribution-team", "hotel-manager"], devices: operatorDevices, prerequisite: "Certified partner contracts, mapping dictionary and acknowledgement receipts", route: "/ecosystem/preview/ai-channel-mapping", operationalPurpose: "Surface mapping drift and failed delivery without silently changing channel configuration.", statusReason: "Preview only: no partner mapping or delivery is performed.", existing: false }),

  record({ key: "crm.guests", module: "crm", label: "Guests", summary: "Guest and party profiles connected to reservation context.", status: "live", audience: ["hotel-operator", "hotel-manager"], devices: operatorDevices, prerequisite: "Authenticated property access", route: "/p/:propertyId/guests", operationalPurpose: "Find guest context while keeping reservation authority intact.", statusReason: "Existing Guests workspace is available.", existing: true }),
  record({ key: "crm.segments", module: "crm", label: "Guest segments", summary: "Audience and repeat-stay segmentation.", status: "planned", audience: ["hotel-manager", "revenue-team"], devices: operatorDevices, prerequisite: "Consent-aware profile and segmentation policy", route: "/ecosystem/preview/guest-segments", operationalPurpose: "Support relevant guest service and commercial decisions.", statusReason: "Planned: segmentation policy and controls are not live.", existing: false }),
  record({ key: "crm.loyalty", module: "crm", label: "Loyalty", summary: "Membership, benefits and recognition.", status: "blocked", audience: ["hotel-manager", "guest"], devices: allDevices, prerequisite: "Approved loyalty policy, identity and liability model", route: "/ecosystem/preview/loyalty", operationalPurpose: "Recognize eligible guests without inventing entitlement or balances.", statusReason: "Blocked pending policy and accounting design.", existing: false }),

  record({ key: "groups-events.sales", module: "groups-events", label: "Groups & sales", summary: "Group blocks, quotes and contracted stays.", status: "planned", audience: ["hotel-manager", "hotel-operator"], devices: operatorDevices, prerequisite: "Group contract, deposit and inventory allocation model", route: "/ecosystem/preview/groups-sales", operationalPurpose: "Coordinate group demand without bypassing reservation and folio authority.", statusReason: "Planned: group contracting is not exposed in this shell.", existing: false }),
  record({ key: "groups-events.event-operations", module: "groups-events", label: "Event operations", summary: "Event run sheets, rooms and service handoffs.", status: "planned", audience: ["hotel-manager", "hotel-operator"], devices: operatorDevices, prerequisite: "Event, task and ancillary contracts", route: "/ecosystem/preview/event-operations", operationalPurpose: "Make event commitments operationally visible.", statusReason: "Planned: no event execution authority is present.", existing: false }),
  record({ key: "groups-events.contracts", module: "groups-events", label: "Group contracts", summary: "Signed group terms and approval checkpoints.", status: "blocked", audience: ["hotel-manager"], devices: operatorDevices, prerequisite: "Contract storage, approval and document numbering policy", route: "/ecosystem/preview/group-contracts", operationalPurpose: "Keep commercial commitments traceable before inventory is held.", statusReason: "Blocked pending document and approval contracts.", existing: false }),

  record({ key: "maintenance-assets.work-orders", module: "maintenance-assets", label: "Maintenance work orders", summary: "Fault reporting, assignment and completion evidence.", status: "planned", audience: ["hotel-operator", "hotel-manager"], devices: allDevices, prerequisite: "Asset registry and maintenance task contract", route: "/ecosystem/preview/maintenance-work-orders", operationalPurpose: "Keep physical work accountable without changing room occupancy authority.", statusReason: "Planned: maintenance tasks are not currently a live workspace.", existing: false }),
  record({ key: "maintenance-assets.asset-register", module: "maintenance-assets", label: "Asset register", summary: "Property assets, warranties and lifecycle context.", status: "preview", audience: ["property-admin", "hotel-manager"], devices: operatorDevices, prerequisite: "Asset identity and custody policy", route: "/ecosystem/preview/asset-register", operationalPurpose: "Give property teams a durable asset reference.", statusReason: "Preview only: no asset database or write authority is attached.", existing: false }),

  record({ key: "food-ancillaries.outlets", module: "food-ancillaries", label: "F&B outlets", summary: "Outlet menus, service periods and guest charges.", status: "planned", audience: ["hotel-manager", "hotel-operator"], devices: allDevices, prerequisite: "Outlet, menu, tax and folio-posting contracts", route: "/ecosystem/preview/fnb-outlets", operationalPurpose: "Coordinate outlet service while preserving folio and tax authority.", statusReason: "Planned: no outlet catalogue or posting flow is live.", existing: false }),
  record({ key: "food-ancillaries.ancillary-bookings", module: "food-ancillaries", label: "Ancillary bookings", summary: "Spa, activities and add-on reservations.", status: "planned", audience: ["hotel-operator", "guest"], devices: allDevices, prerequisite: "Ancillary inventory, payment and cancellation policies", route: "/ecosystem/preview/ancillary-bookings", operationalPurpose: "Sell and fulfil extras without creating phantom inventory.", statusReason: "Planned: no ancillary inventory command is exposed.", existing: false }),

  record({ key: "purchasing-inventory.inventory", module: "purchasing-inventory", label: "Purchasing & inventory", summary: "Stock, suppliers and replenishment planning.", status: "planned", audience: ["hotel-manager", "property-admin"], devices: operatorDevices, prerequisite: "Item, supplier, unit and stock-ledger contracts", route: "/ecosystem/preview/purchasing-inventory", operationalPurpose: "Protect operational supply without conflating stock with room sellability.", statusReason: "Planned: no purchasing or stock authority is connected to this shell.", existing: false }),
  record({ key: "purchasing-inventory.suppliers", module: "purchasing-inventory", label: "Supplier catalogue", summary: "Approved suppliers and purchasing terms.", status: "blocked", audience: ["property-admin", "finance-team"], devices: operatorDevices, prerequisite: "Supplier onboarding, tax and payment policy", route: "/ecosystem/preview/suppliers", operationalPurpose: "Keep supplier identity and terms reviewable before a purchase order.", statusReason: "Blocked pending supplier and payables policy.", existing: false }),

  record({ key: "analytics.performance", module: "analytics", label: "Performance", summary: "Current commercial performance comparisons.", status: "beta", audience: ["hotel-manager", "revenue-team"], devices: operatorDevices, prerequisite: "Current rates and performance reads", route: "/p/:propertyId/today?workspace=rates", operationalPurpose: "Compare current configured commercial performance without inventing forecasts.", statusReason: "Available inside the existing rates workspace with bounded metrics.", existing: true }),
  record({ key: "analytics.property-analytics", module: "analytics", label: "Property analytics", summary: "A coherent property-wide decision surface.", status: "preview", audience: ["hotel-manager", "finance-team", "revenue-team"], devices: operatorDevices, prerequisite: "Metric catalogue, freshness and tenancy contracts", route: "/ecosystem/preview/property-analytics", operationalPurpose: "Make cross-domain metrics explainable and source-bound.", statusReason: "Preview only: no broad analytics authority is being simulated.", existing: false }),
  record({ key: "analytics.activity-investigation", module: "analytics", label: "Activity investigation", summary: "A cross-linked timeline of user actions, receipts, failures and affected records.", status: "preview", audience: ["hotel-manager", "property-admin"], devices: operatorDevices, prerequisite: "Access-filtered event catalogue, correlation identifiers and retention policy", route: "/ecosystem/preview/activity-investigation", operationalPurpose: "Answer what happened without turning audit evidence into an unrestricted data browser.", statusReason: "Preview only: the event catalogue is not exposed by this shell.", existing: false }),

  record({ key: "compliance.audit", module: "compliance", label: "Audit & evidence", summary: "Operational evidence, receipts and review boundaries.", status: "planned", audience: ["hotel-manager", "property-admin"], devices: operatorDevices, prerequisite: "Accepted evidence catalogue and retention policy", route: "/ecosystem/preview/audit-evidence", operationalPurpose: "Help reviewers trace actions without exposing unrestricted data.", statusReason: "Planned: existing event records are not a standalone audit UI.", existing: false }),
  record({ key: "compliance.privacy", module: "compliance", label: "Privacy controls", summary: "Consent, access and retention controls.", status: "blocked", audience: ["property-admin", "hotel-manager"], devices: operatorDevices, prerequisite: "Jurisdictional policy and data-subject workflow", route: "/ecosystem/preview/privacy-controls", operationalPurpose: "Make privacy decisions explicit before profile or messaging features expand.", statusReason: "Blocked pending the property's policy and jurisdiction choices.", existing: false }),

  record({ key: "property-setup.settings", module: "property-setup", label: "Property setup", summary: "Property identity, timezone and commercial configuration.", status: "live", audience: ["property-admin", "hotel-manager"], devices: operatorDevices, prerequisite: "Authenticated property access", route: "/p/:propertyId/today?workspace=settings", operationalPurpose: "Review the property settings that bound operational decisions.", statusReason: "Existing property settings workspace is available.", existing: true }),
  record({ key: "property-setup.users-roles", module: "property-setup", label: "Users & roles", summary: "Staff identity and least-privilege access.", status: "planned", audience: ["property-admin"], devices: operatorDevices, prerequisite: "Identity provider and role policy", route: "/ecosystem/preview/users-roles", operationalPurpose: "Keep staff access aligned with governed capabilities.", statusReason: "Planned: no user-admin editor is exposed in this preview.", existing: false }),
  record({ key: "property-setup.portfolio-standards", module: "property-setup", label: "Portfolio standards & exceptions", summary: "Brand standards, property overrides and exception approval in one review surface.", status: "preview", audience: ["property-admin", "hotel-manager"], devices: operatorDevices, prerequisite: "Portfolio hierarchy, effective dating and approval policy", route: "/ecosystem/preview/portfolio-standards", operationalPurpose: "Show exactly where a property differs from the approved operating standard.", statusReason: "Preview only: no configuration or exception is changed.", existing: false }),
  record({ key: "property-setup.action-palette", module: "property-setup", label: "Contextual action palette", summary: "A clean Options surface that reveals detailed commands only for the selected record.", status: "preview", audience: ["hotel-operator", "hotel-manager", "property-admin"], devices: operatorDevices, prerequisite: "Capability-aware action registry and per-command eligibility", route: "/ecosystem/preview/contextual-action-palette", operationalPurpose: "Keep dense PMS controls available without overwhelming every primary screen.", statusReason: "Preview only: the palette lists no unaccepted operational command.", existing: false }),

  record({ key: "integrations.connector-registry", module: "integrations", label: "Connector registry", summary: "Partner contracts, health and certification state.", status: "preview", audience: ["property-admin", "distribution-team"], devices: operatorDevices, prerequisite: "Connector contract and secret boundary", route: "/ecosystem/preview/connector-registry", operationalPurpose: "Expose connector readiness without exposing credentials or making network calls.", statusReason: "Preview only: no provider connector is activated by this screen.", existing: false }),
  record({ key: "integrations.webhooks", module: "integrations", label: "Webhooks & events", summary: "Outbound event subscriptions and delivery evidence.", status: "blocked", audience: ["property-admin", "distribution-team"], devices: operatorDevices, prerequisite: "Event contract, endpoint verification and replay policy", route: "/ecosystem/preview/webhooks", operationalPurpose: "Make external delivery auditable when a governed endpoint exists.", statusReason: "Blocked pending endpoint verification and replay controls.", existing: false }),

  record({ key: "guest-mobile.portal", module: "guest-mobile", label: "Guest portal", summary: "A mobile stay companion for approved guest self-service.", status: "planned", audience: ["guest"], devices: ["mobile", "tablet"], prerequisite: "Guest identity, consent and stay-scope contract", route: "/ecosystem/preview/guest-portal", operationalPurpose: "Offer self-service without exposing staff controls or private data.", statusReason: "Planned: no guest-facing portal is live in this shell.", existing: false }),
  record({ key: "guest-mobile.mobile-check-in", module: "guest-mobile", label: "Mobile check-in", summary: "A guest-led check-in preparation flow.", status: "blocked", audience: ["guest", "hotel-operator"], devices: ["mobile", "tablet"], prerequisite: "Identity, payment edge, document and arrival policy", route: "/ecosystem/preview/mobile-check-in", operationalPurpose: "Reduce arrival friction while keeping eligibility server-owned.", statusReason: "Blocked pending identity, document and payment-edge contracts.", existing: false }),
  record({ key: "guest-mobile.staff-mobile", module: "guest-mobile", label: "Staff mobile", summary: "Mobile operational tasks for approved staff roles.", status: "preview", audience: ["hotel-operator", "hotel-manager"], devices: ["mobile", "tablet"], prerequisite: "Offline, identity and task-sync policy", route: "/ecosystem/preview/staff-mobile", operationalPurpose: "Bring bounded task visibility to staff devices without weakening authority.", statusReason: "Preview only: no offline or mobile task writer is enabled.", existing: false }),
  record({ key: "guest-mobile.non-room-scheduler", module: "guest-mobile", label: "Non-room resource scheduler", summary: "Time-based availability for luggage pickup, transport, spa, equipment and shared spaces.", status: "preview", audience: ["guest", "hotel-operator"], devices: allDevices, prerequisite: "Resource inventory, service windows, fulfilment ownership and guest identity", route: "/ecosystem/preview/non-room-resource-scheduler", operationalPurpose: "Offer immediate or scheduled service without inventing capacity or confirmation.", statusReason: "Preview only: no resource booking or department message is sent.", existing: false }),
]);

export const ECOSYSTEM_CAPABILITIES = CAPABILITY_REGISTRY;

export function capabilitiesForModule(module: EcosystemModule): readonly CapabilityRecord[] {
  return CAPABILITY_REGISTRY.filter((capability) => capability.module === module);
}

export function capabilityByKey(key: string): CapabilityRecord | undefined {
  return CAPABILITY_REGISTRY.find((capability) => capability.key === key);
}

export function isOperationalCapability(capability: CapabilityRecord): boolean {
  return capability.status === "live" || capability.status === "beta";
}
